In [2]:
import numpy as np

In [4]:
#Inicialmente, definimos o número de unidades de cada camada, bem como o tamanho do training-set:

s=10000 #número de elementos do training-set
l1=1  #número de unidades da camada 1, ou seja, input layer
l2=2  #número de unidades da camada 2, ou seja, a primeira hidden layer
l3=1  #número de unidades da camada 3, ou seja, a segunda hidden layer

#A seguir definimos o training set:

X=np.random.rand(s)[None,:]  #valores de entrada para o treinamento. Fazemos [None,:] para "tornar" o vetor uma "matriz de uma única linha", de modo a podermos realizar o "produto matricial" adiante
e=np.tanh(X)   #vetor dos valores esperados associados a X: nesse caso, a própria função tanh para teste do MLP 

#Nesta etapa, inicializamos os vetores peso e o vetor de bias:

W12=np.ones(l2*l1).reshape(l2,l1)  #vetor peso que conecta a camada 1 à 2
W23=np.ones((l2*l3)+1).reshape(l2+1,l3) #vetor peso que conecta a camada 2 à 3. O +1 corresponde ao peso que multiplicará o vetor de bias
b=np.ones(X.size) #vetor de bias

n=0.00005  #taxa de aprendizagem (obtida por tentativa e erro)
num_iter=5000  #número de rodadas que o training set alimentará o MLP

In [5]:
#Finalmente, realizamos o treinamento:
    
for j in range(num_iter):
    
    #primeiramente, calculamos o output gerado pelo perceptron em cada rodada:
    
    S2=np.dot(W12,X)  #S2 é o vetor que contém os valores de entrada para cada unidade da camada 2. np.dot equivale  ao produto matricial
    F2=np.tanh(S2)   #Aplicamos a função de ativação element-wise: tangente hiperbolica
    F2=np.vstack((F2,b)) #unimos o vetor de bias a F2 a cada rodada.
    Y=(F2*W23).sum(axis=0)  #calculamos então o output Y

    #em seguida, calculamos os gradientes e atualizamos os pesos:
    
    gradW23=(2*(Y-e)*F2).sum(axis=1)[:,None] #gradiente de W23. Fazemos [:,None] para tornar possível o broadcast com W23.
    W23=W23-n*gradW23 #atualizamos o vetor W23, pois o mesmo será utilizado no calculo do gradiente de W12

    gradW12=2*(((((Y-e)*X)*W23[0:2,:])*(1 - (np.tanh(S2))**2)).sum(axis=1))[:,None] #gradiente de W12. Fazemos o slice em W23, pois para o cálculo de W12 só nos interessa as duas primeiras linhas de W23, já que a última linha corresponde ao vetor de bias.
    W12=W12-n*gradW12 #atualizamos W12
    
    print('\n \n rodada' ,j,":")
    print('\n gradW12: \n',gradW12)
    print('\n gradW23: \n',gradW23)
    print('\n W12: \n',W12)
    print('\n W23: \n', W23)


 
 rodada 0 :

 gradW12: 
 [[ 3297.2630523]
 [ 3297.2630523]]

 gradW23: 
 [[ 13340.0634392 ]
 [ 13340.0634392 ]
 [ 28613.27137236]]

 W12: 
 [[ 0.83513685]
 [ 0.83513685]]

 W23: 
 [[ 0.33299683]
 [ 0.33299683]
 [-0.43066357]]

 
 rodada 1 :

 gradW12: 
 [[-2767.64754199]
 [-2767.64754199]]

 gradW23: 
 [[ -4945.54425909]
 [ -4945.54425909]
 [-12248.12720133]]

 W12: 
 [[ 0.97351922]
 [ 0.97351922]]

 W23: 
 [[ 0.58027404]
 [ 0.58027404]
 [ 0.18174279]]

 
 rodada 2 :

 gradW12: 
 [[ 793.96788049]
 [ 793.96788049]]

 gradW23: 
 [[ 2174.81541387]
 [ 2174.81541387]
 [ 4815.61535358]]

 W12: 
 [[ 0.93382083]
 [ 0.93382083]]

 W23: 
 [[ 0.47153327]
 [ 0.47153327]
 [-0.05903798]]

 
 rodada 3 :

 gradW12: 
 [[-402.11819777]
 [-402.11819777]]

 gradW23: 
 [[ -945.12260171]
 [ -945.12260171]
 [-2087.37179948]]

 W12: 
 [[ 0.95392674]
 [ 0.95392674]]

 W23: 
 [[ 0.5187894 ]
 [ 0.5187894 ]
 [ 0.04533061]]

 
 rodada 4 :

 gradW12: 
 [[ 155.66198693]
 [ 155.66198693]]

 gradW23: 
 [[ 388.74943


 W23: 
 [[ 0.51416127]
 [ 0.51416127]
 [ 0.00370515]]

 
 rodada 59 :

 gradW12: 
 [[-0.78398154]
 [-0.78398154]]

 gradW23: 
 [[ 0.01408523]
 [ 0.01408523]
 [ 0.27620175]]

 W12: 
 [[ 0.95338064]
 [ 0.95338064]]

 W23: 
 [[ 0.51416056]
 [ 0.51416056]
 [ 0.00369134]]

 
 rodada 60 :

 gradW12: 
 [[-0.77872733]
 [-0.77872733]]

 gradW23: 
 [[ 0.03028591]
 [ 0.03028591]
 [ 0.25969969]]

 W12: 
 [[ 0.95341958]
 [ 0.95341958]]

 W23: 
 [[ 0.51415905]
 [ 0.51415905]
 [ 0.00367835]]

 
 rodada 61 :

 gradW12: 
 [[-0.77382466]
 [-0.77382466]]

 gradW23: 
 [[ 0.04527084]
 [ 0.04527084]
 [ 0.24441837]]

 W12: 
 [[ 0.95345827]
 [ 0.95345827]]

 W23: 
 [[ 0.51415678]
 [ 0.51415678]
 [ 0.00366613]]

 
 rodada 62 :

 gradW12: 
 [[-0.76924746]
 [-0.76924746]]

 gradW23: 
 [[ 0.05913016]
 [ 0.05913016]
 [ 0.23026731]]

 W12: 
 [[ 0.95349673]
 [ 0.95349673]]

 W23: 
 [[ 0.51415383]
 [ 0.51415383]
 [ 0.00365462]]

 
 rodada 63 :

 gradW12: 
 [[-0.76497159]
 [-0.76497159]]

 gradW23: 
 [[ 0.07194735]
 

 rodada 115 :

 gradW12: 
 [[-0.69229061]
 [-0.69229061]]

 gradW23: 
 [[ 0.22152913]
 [ 0.22152913]
 [ 0.05507246]]

 W12: 
 [[ 0.95539528]
 [ 0.95539528]]

 W23: 
 [[ 0.5136536 ]
 [ 0.5136536 ]
 [ 0.00340587]]

 
 rodada 116 :

 gradW12: 
 [[-0.69172191]
 [-0.69172191]]

 gradW23: 
 [[ 0.22156265]
 [ 0.22156265]
 [ 0.05481574]]

 W12: 
 [[ 0.95542986]
 [ 0.95542986]]

 W23: 
 [[ 0.51364252]
 [ 0.51364252]
 [ 0.00340313]]

 
 rodada 117 :

 gradW12: 
 [[-0.6911582]
 [-0.6911582]]

 gradW23: 
 [[ 0.2215801 ]
 [ 0.2215801 ]
 [ 0.05457534]]

 W12: 
 [[ 0.95546442]
 [ 0.95546442]]

 W23: 
 [[ 0.51363144]
 [ 0.51363144]
 [ 0.0034004 ]]

 
 rodada 118 :

 gradW12: 
 [[-0.69059912]
 [-0.69059912]]

 gradW23: 
 [[ 0.22158268]
 [ 0.22158268]
 [ 0.05435006]]

 W12: 
 [[ 0.95549895]
 [ 0.95549895]]

 W23: 
 [[ 0.51362036]
 [ 0.51362036]
 [ 0.00339768]]

 
 rodada 119 :

 gradW12: 
 [[-0.69004435]
 [-0.69004435]]

 gradW23: 
 [[ 0.2215715 ]
 [ 0.2215715 ]
 [ 0.05413878]]

 W12: 
 [[ 0.95553345]
 

 rodada 177 :

 gradW12: 
 [[-0.66068589]
 [-0.66068589]]

 gradW23: 
 [[ 0.21325976]
 [ 0.21325976]
 [ 0.04988076]]

 W12: 
 [[ 0.95749051]
 [ 0.95749051]]

 W23: 
 [[ 0.51297732]
 [ 0.51297732]
 [ 0.00324607]]

 
 rodada 178 :

 gradW12: 
 [[-0.66019908]
 [-0.66019908]]

 gradW23: 
 [[ 0.21308578]
 [ 0.21308578]
 [ 0.04984318]]

 W12: 
 [[ 0.95752352]
 [ 0.95752352]]

 W23: 
 [[ 0.51296667]
 [ 0.51296667]
 [ 0.00324357]]

 
 rodada 179 :

 gradW12: 
 [[-0.65971263]
 [-0.65971263]]

 gradW23: 
 [[ 0.21291181]
 [ 0.21291181]
 [ 0.04980577]]

 W12: 
 [[ 0.95755651]
 [ 0.95755651]]

 W23: 
 [[ 0.51295602]
 [ 0.51295602]
 [ 0.00324108]]

 
 rodada 180 :

 gradW12: 
 [[-0.65922653]
 [-0.65922653]]

 gradW23: 
 [[ 0.21273786]
 [ 0.21273786]
 [ 0.0497685 ]]

 W12: 
 [[ 0.95758947]
 [ 0.95758947]]

 W23: 
 [[ 0.51294539]
 [ 0.51294539]
 [ 0.0032386 ]]

 
 rodada 181 :

 gradW12: 
 [[-0.65874077]
 [-0.65874077]]

 gradW23: 
 [[ 0.21256394]
 [ 0.21256394]
 [ 0.04973137]]

 W12: 
 [[ 0.9576224]


 [[ 0.95898405]
 [ 0.95898405]]

 W23: 
 [[ 0.51249617]
 [ 0.51249617]
 [ 0.0031333 ]]

 
 rodada 224 :

 gradW12: 
 [[-0.63816121]
 [-0.63816121]]

 gradW23: 
 [[ 0.20517571]
 [ 0.20517571]
 [ 0.0482001 ]]

 W12: 
 [[ 0.95901595]
 [ 0.95901595]]

 W23: 
 [[ 0.51248591]
 [ 0.51248591]
 [ 0.00313089]]

 
 rodada 225 :

 gradW12: 
 [[-0.63768953]
 [-0.63768953]]

 gradW23: 
 [[ 0.20500664]
 [ 0.20500664]
 [ 0.04816532]]

 W12: 
 [[ 0.95904784]
 [ 0.95904784]]

 W23: 
 [[ 0.51247566]
 [ 0.51247566]
 [ 0.00312848]]

 
 rodada 226 :

 gradW12: 
 [[-0.63721817]
 [-0.63721817]]

 gradW23: 
 [[ 0.20483771]
 [ 0.20483771]
 [ 0.04813056]]

 W12: 
 [[ 0.9590797]
 [ 0.9590797]]

 W23: 
 [[ 0.51246542]
 [ 0.51246542]
 [ 0.00312607]]

 
 rodada 227 :

 gradW12: 
 [[-0.63674712]
 [-0.63674712]]

 gradW23: 
 [[ 0.20466892]
 [ 0.20466892]
 [ 0.04809583]]

 W12: 
 [[ 0.95911154]
 [ 0.95911154]]

 W23: 
 [[ 0.51245518]
 [ 0.51245518]
 [ 0.00312367]]

 
 rodada 228 :

 gradW12: 
 [[-0.63627637]
 [-0.63627


 
 rodada 288 :

 gradW12: 
 [[-0.60859027]
 [-0.60859027]]

 gradW23: 
 [[ 0.19462975]
 [ 0.19462975]
 [ 0.04601892]]

 W12: 
 [[ 0.96100968]
 [ 0.96100968]]

 W23: 
 [[ 0.51184663]
 [ 0.51184663]
 [ 0.00298021]]

 
 rodada 289 :

 gradW12: 
 [[-0.60813806]
 [-0.60813806]]

 gradW23: 
 [[ 0.19446935]
 [ 0.19446935]
 [ 0.04598552]]

 W12: 
 [[ 0.96104009]
 [ 0.96104009]]

 W23: 
 [[ 0.51183691]
 [ 0.51183691]
 [ 0.00297792]]

 
 rodada 290 :

 gradW12: 
 [[-0.60768614]
 [-0.60768614]]

 gradW23: 
 [[ 0.19430908]
 [ 0.19430908]
 [ 0.04595215]]

 W12: 
 [[ 0.96107048]
 [ 0.96107048]]

 W23: 
 [[ 0.51182719]
 [ 0.51182719]
 [ 0.00297562]]

 
 rodada 291 :

 gradW12: 
 [[-0.60723453]
 [-0.60723453]]

 gradW23: 
 [[ 0.19414893]
 [ 0.19414893]
 [ 0.04591881]]

 W12: 
 [[ 0.96110084]
 [ 0.96110084]]

 W23: 
 [[ 0.51181749]
 [ 0.51181749]
 [ 0.00297332]]

 
 rodada 292 :

 gradW12: 
 [[-0.60678321]
 [-0.60678321]]

 gradW23: 
 [[ 0.19398893]
 [ 0.19398893]
 [ 0.04588548]]

 W12: 
 [[ 0.961131

 [[-0.5819826]
 [-0.5819826]]

 gradW23: 
 [[ 0.18523626]
 [ 0.18523626]
 [ 0.04405202]]

 W12: 
 [[ 0.96279461]
 [ 0.96279461]]

 W23: 
 [[ 0.51127719]
 [ 0.51127719]
 [ 0.00284518]]

 
 rodada 349 :

 gradW12: 
 [[-0.58154811]
 [-0.58154811]]

 gradW23: 
 [[ 0.18508362]
 [ 0.18508362]
 [ 0.04401987]]

 W12: 
 [[ 0.96282369]
 [ 0.96282369]]

 W23: 
 [[ 0.51126793]
 [ 0.51126793]
 [ 0.00284297]]

 
 rodada 350 :

 gradW12: 
 [[-0.5811139]
 [-0.5811139]]

 gradW23: 
 [[ 0.1849311 ]
 [ 0.1849311 ]
 [ 0.04398773]]

 W12: 
 [[ 0.96285275]
 [ 0.96285275]]

 W23: 
 [[ 0.51125869]
 [ 0.51125869]
 [ 0.00284078]]

 
 rodada 351 :

 gradW12: 
 [[-0.58067999]
 [-0.58067999]]

 gradW23: 
 [[ 0.1847787 ]
 [ 0.1847787 ]
 [ 0.04395561]]

 W12: 
 [[ 0.96288178]
 [ 0.96288178]]

 W23: 
 [[ 0.51124945]
 [ 0.51124945]
 [ 0.00283858]]

 
 rodada 352 :

 gradW12: 
 [[-0.58024637]
 [-0.58024637]]

 gradW23: 
 [[ 0.18462644]
 [ 0.18462644]
 [ 0.04392352]]

 W12: 
 [[ 0.96291079]
 [ 0.96291079]]

 W23: 
 [[ 0


 
 rodada 400 :

 gradW12: 
 [[-0.55977181]
 [-0.55977181]]

 gradW23: 
 [[ 0.17746376]
 [ 0.17746376]
 [ 0.04240669]]

 W12: 
 [[ 0.96427817]
 [ 0.96427817]]

 W23: 
 [[ 0.51080594]
 [ 0.51080594]
 [ 0.00273283]]

 
 rodada 401 :

 gradW12: 
 [[-0.55935227]
 [-0.55935227]]

 gradW23: 
 [[ 0.17731754]
 [ 0.17731754]
 [ 0.04237559]]

 W12: 
 [[ 0.96430614]
 [ 0.96430614]]

 W23: 
 [[ 0.51079708]
 [ 0.51079708]
 [ 0.00273071]]

 
 rodada 402 :

 gradW12: 
 [[-0.55893301]
 [-0.55893301]]

 gradW23: 
 [[ 0.17717145]
 [ 0.17717145]
 [ 0.0423445 ]]

 W12: 
 [[ 0.96433408]
 [ 0.96433408]]

 W23: 
 [[ 0.51078822]
 [ 0.51078822]
 [ 0.0027286 ]]

 
 rodada 403 :

 gradW12: 
 [[-0.55851404]
 [-0.55851404]]

 gradW23: 
 [[ 0.17702547]
 [ 0.17702547]
 [ 0.04231343]]

 W12: 
 [[ 0.96436201]
 [ 0.96436201]]

 W23: 
 [[ 0.51077937]
 [ 0.51077937]
 [ 0.00272648]]

 
 rodada 404 :

 gradW12: 
 [[-0.55809535]
 [-0.55809535]]

 gradW23: 
 [[ 0.17687961]
 [ 0.17687961]
 [ 0.04228238]]

 W12: 
 [[ 0.964389

 rodada 459 :

 gradW12: 
 [[-0.53549989]
 [-0.53549989]]

 gradW23: 
 [[ 0.16904046]
 [ 0.16904046]
 [ 0.04060512]]

 W12: 
 [[ 0.96589285]
 [ 0.96589285]]

 W23: 
 [[ 0.51029516]
 [ 0.51029516]
 [ 0.00261045]]

 
 rodada 460 :

 gradW12: 
 [[-0.53509686]
 [-0.53509686]]

 gradW23: 
 [[ 0.1689012 ]
 [ 0.1689012 ]
 [ 0.04057518]]

 W12: 
 [[ 0.9659196]
 [ 0.9659196]]

 W23: 
 [[ 0.51028672]
 [ 0.51028672]
 [ 0.00260842]]

 
 rodada 461 :

 gradW12: 
 [[-0.5346941]
 [-0.5346941]]

 gradW23: 
 [[ 0.16876206]
 [ 0.16876206]
 [ 0.04054525]]

 W12: 
 [[ 0.96594634]
 [ 0.96594634]]

 W23: 
 [[ 0.51027828]
 [ 0.51027828]
 [ 0.0026064 ]]

 
 rodada 462 :

 gradW12: 
 [[-0.53429161]
 [-0.53429161]]

 gradW23: 
 [[ 0.16862304]
 [ 0.16862304]
 [ 0.04051534]]

 W12: 
 [[ 0.96597305]
 [ 0.96597305]]

 W23: 
 [[ 0.51026985]
 [ 0.51026985]
 [ 0.00260437]]

 
 rodada 463 :

 gradW12: 
 [[-0.5338894]
 [-0.5338894]]

 gradW23: 
 [[ 0.16848413]
 [ 0.16848413]
 [ 0.04048545]]

 W12: 
 [[ 0.96599975]
 [ 0.

 [[ 0.50980862]
 [ 0.50980862]
 [ 0.00249328]]

 
 rodada 519 :

 gradW12: 
 [[-0.51180044]
 [-0.51180044]]

 gradW23: 
 [[ 0.16088583]
 [ 0.16088583]
 [ 0.0388425 ]]

 W12: 
 [[ 0.96746296]
 [ 0.96746296]]

 W23: 
 [[ 0.50980058]
 [ 0.50980058]
 [ 0.00249134]]

 
 rodada 520 :

 gradW12: 
 [[-0.51141369]
 [-0.51141369]]

 gradW23: 
 [[ 0.16075332]
 [ 0.16075332]
 [ 0.03881371]]

 W12: 
 [[ 0.96748853]
 [ 0.96748853]]

 W23: 
 [[ 0.50979254]
 [ 0.50979254]
 [ 0.0024894 ]]

 
 rodada 521 :

 gradW12: 
 [[-0.51102719]
 [-0.51102719]]

 gradW23: 
 [[ 0.16062092]
 [ 0.16062092]
 [ 0.03878493]]

 W12: 
 [[ 0.96751409]
 [ 0.96751409]]

 W23: 
 [[ 0.50978451]
 [ 0.50978451]
 [ 0.00248746]]

 
 rodada 522 :

 gradW12: 
 [[-0.51064097]
 [-0.51064097]]

 gradW23: 
 [[ 0.16048863]
 [ 0.16048863]
 [ 0.03875618]]

 W12: 
 [[ 0.96753962]
 [ 0.96753962]]

 W23: 
 [[ 0.50977648]
 [ 0.50977648]
 [ 0.00248552]]

 
 rodada 523 :

 gradW12: 
 [[-0.51025501]
 [-0.51025501]]

 gradW23: 
 [[ 0.16035645]
 [ 0

 rodada 579 :

 gradW12: 
 [[-0.48906264]
 [-0.48906264]]

 gradW23: 
 [[ 0.15312621]
 [ 0.15312621]
 [ 0.03714815]]

 W12: 
 [[ 0.96896345]
 [ 0.96896345]]

 W23: 
 [[ 0.50932985]
 [ 0.50932985]
 [ 0.00237742]]

 
 rodada 580 :

 gradW12: 
 [[-0.48869165]
 [-0.48869165]]

 gradW23: 
 [[ 0.15300012]
 [ 0.15300012]
 [ 0.03712048]]

 W12: 
 [[ 0.96898789]
 [ 0.96898789]]

 W23: 
 [[ 0.5093222 ]
 [ 0.5093222 ]
 [ 0.00237556]]

 
 rodada 581 :

 gradW12: 
 [[-0.48832092]
 [-0.48832092]]

 gradW23: 
 [[ 0.15287414]
 [ 0.15287414]
 [ 0.03709283]]

 W12: 
 [[ 0.9690123]
 [ 0.9690123]]

 W23: 
 [[ 0.50931455]
 [ 0.50931455]
 [ 0.0023737 ]]

 
 rodada 582 :

 gradW12: 
 [[-0.48795045]
 [-0.48795045]]

 gradW23: 
 [[ 0.15274825]
 [ 0.15274825]
 [ 0.03706519]]

 W12: 
 [[ 0.9690367]
 [ 0.9690367]]

 W23: 
 [[ 0.50930692]
 [ 0.50930692]
 [ 0.00237185]]

 
 rodada 583 :

 gradW12: 
 [[-0.48758023]
 [-0.48758023]]

 gradW23: 
 [[ 0.15262248]
 [ 0.15262248]
 [ 0.03703758]]

 W12: 
 [[ 0.96906108]
 [ 

 rodada 636 :

 gradW12: 
 [[-0.46832454]
 [-0.46832454]]

 gradW23: 
 [[ 0.14610305]
 [ 0.14610305]
 [ 0.03560007]]

 W12: 
 [[ 0.97032701]
 [ 0.97032701]]

 W23: 
 [[ 0.5089037]
 [ 0.5089037]
 [ 0.0022738]]

 
 rodada 637 :

 gradW12: 
 [[-0.46796806]
 [-0.46796806]]

 gradW23: 
 [[ 0.14598277]
 [ 0.14598277]
 [ 0.03557344]]

 W12: 
 [[ 0.97035041]
 [ 0.97035041]]

 W23: 
 [[ 0.5088964 ]
 [ 0.5088964 ]
 [ 0.00227202]]

 
 rodada 638 :

 gradW12: 
 [[-0.46761182]
 [-0.46761182]]

 gradW23: 
 [[ 0.14586259]
 [ 0.14586259]
 [ 0.03554682]]

 W12: 
 [[ 0.97037379]
 [ 0.97037379]]

 W23: 
 [[ 0.50888911]
 [ 0.50888911]
 [ 0.00227025]]

 
 rodada 639 :

 gradW12: 
 [[-0.46725584]
 [-0.46725584]]

 gradW23: 
 [[ 0.14574251]
 [ 0.14574251]
 [ 0.03552022]]

 W12: 
 [[ 0.97039716]
 [ 0.97039716]]

 W23: 
 [[ 0.50888182]
 [ 0.50888182]
 [ 0.00226847]]

 
 rodada 640 :

 gradW12: 
 [[-0.46690011]
 [-0.46690011]]

 gradW23: 
 [[ 0.14562252]
 [ 0.14562252]
 [ 0.03549364]]

 W12: 
 [[ 0.9704205]
 [ 


 
 rodada 696 :

 gradW12: 
 [[-0.44737391]
 [-0.44737391]]

 gradW23: 
 [[ 0.13905959]
 [ 0.13905959]
 [ 0.0340335 ]]

 W12: 
 [[ 0.97169982]
 [ 0.97169982]]

 W23: 
 [[ 0.50847622]
 [ 0.50847622]
 [ 0.00216941]]

 
 rodada 697 :

 gradW12: 
 [[-0.4470322]
 [-0.4470322]]

 gradW23: 
 [[ 0.13894514]
 [ 0.13894514]
 [ 0.03400792]]

 W12: 
 [[ 0.97172217]
 [ 0.97172217]]

 W23: 
 [[ 0.50846927]
 [ 0.50846927]
 [ 0.00216771]]

 
 rodada 698 :

 gradW12: 
 [[-0.44669073]
 [-0.44669073]]

 gradW23: 
 [[ 0.13883078]
 [ 0.13883078]
 [ 0.03398237]]

 W12: 
 [[ 0.9717445]
 [ 0.9717445]]

 W23: 
 [[ 0.50846233]
 [ 0.50846233]
 [ 0.00216601]]

 
 rodada 699 :

 gradW12: 
 [[-0.44634951]
 [-0.44634951]]

 gradW23: 
 [[ 0.13871651]
 [ 0.13871651]
 [ 0.03395683]]

 W12: 
 [[ 0.97176682]
 [ 0.97176682]]

 W23: 
 [[ 0.5084554 ]
 [ 0.5084554 ]
 [ 0.00216431]]

 
 rodada 700 :

 gradW12: 
 [[-0.44600853]
 [-0.44600853]]

 gradW23: 
 [[ 0.13860235]
 [ 0.13860235]
 [ 0.03393131]]

 W12: 
 [[ 0.97178912]


 rodada 755 :

 gradW12: 
 [[-0.42762262]
 [-0.42762262]]

 gradW23: 
 [[ 0.13246635]
 [ 0.13246635]
 [ 0.03255421]]

 W12: 
 [[ 0.97298974]
 [ 0.97298974]]

 W23: 
 [[ 0.50807596]
 [ 0.50807596]
 [ 0.00207124]]

 
 rodada 756 :

 gradW12: 
 [[-0.42729495]
 [-0.42729495]]

 gradW23: 
 [[ 0.13235735]
 [ 0.13235735]
 [ 0.03252965]]

 W12: 
 [[ 0.9730111]
 [ 0.9730111]]

 W23: 
 [[ 0.50806935]
 [ 0.50806935]
 [ 0.00206961]]

 
 rodada 757 :

 gradW12: 
 [[-0.42696752]
 [-0.42696752]]

 gradW23: 
 [[ 0.13224845]
 [ 0.13224845]
 [ 0.03250511]]

 W12: 
 [[ 0.97303245]
 [ 0.97303245]]

 W23: 
 [[ 0.50806273]
 [ 0.50806273]
 [ 0.00206799]]

 
 rodada 758 :

 gradW12: 
 [[-0.42664032]
 [-0.42664032]]

 gradW23: 
 [[ 0.13213963]
 [ 0.13213963]
 [ 0.03248058]]

 W12: 
 [[ 0.97305378]
 [ 0.97305378]]

 W23: 
 [[ 0.50805613]
 [ 0.50805613]
 [ 0.00206637]]

 
 rodada 759 :

 gradW12: 
 [[-0.42631335]
 [-0.42631335]]

 gradW23: 
 [[ 0.1320309 ]
 [ 0.1320309 ]
 [ 0.03245607]]

 W12: 
 [[ 0.9730751]
 [


 
 rodada 817 :

 gradW12: 
 [[-0.40774402]
 [-0.40774402]]

 gradW23: 
 [[ 0.12587615]
 [ 0.12587615]
 [ 0.03106307]]

 W12: 
 [[ 0.97428383]
 [ 0.97428383]]

 W23: 
 [[ 0.50767578]
 [ 0.50767578]
 [ 0.00197269]]

 
 rodada 818 :

 gradW12: 
 [[-0.40743058]
 [-0.40743058]]

 gradW23: 
 [[ 0.1257726 ]
 [ 0.1257726 ]
 [ 0.03103954]]

 W12: 
 [[ 0.9743042]
 [ 0.9743042]]

 W23: 
 [[ 0.5076695 ]
 [ 0.5076695 ]
 [ 0.00197114]]

 
 rodada 819 :

 gradW12: 
 [[-0.40711738]
 [-0.40711738]]

 gradW23: 
 [[ 0.12566914]
 [ 0.12566914]
 [ 0.03101603]]

 W12: 
 [[ 0.97432456]
 [ 0.97432456]]

 W23: 
 [[ 0.50766321]
 [ 0.50766321]
 [ 0.00196959]]

 
 rodada 820 :

 gradW12: 
 [[-0.40680439]
 [-0.40680439]]

 gradW23: 
 [[ 0.12556577]
 [ 0.12556577]
 [ 0.03099253]]

 W12: 
 [[ 0.9743449]
 [ 0.9743449]]

 W23: 
 [[ 0.50765693]
 [ 0.50765693]
 [ 0.00196804]]

 
 rodada 821 :

 gradW12: 
 [[-0.40649163]
 [-0.40649163]]

 gradW23: 
 [[ 0.12546248]
 [ 0.12546248]
 [ 0.03096905]]

 W12: 
 [[ 0.97436523]


 rodada 878 :

 gradW12: 
 [[-0.38903196]
 [-0.38903196]]

 gradW23: 
 [[ 0.11971396]
 [ 0.11971396]
 [ 0.02965733]]

 W12: 
 [[ 0.97549824]
 [ 0.97549824]]

 W23: 
 [[ 0.50730149]
 [ 0.50730149]
 [ 0.00188014]]

 
 rodada 879 :

 gradW12: 
 [[-0.38873202]
 [-0.38873202]]

 gradW23: 
 [[ 0.11961551]
 [ 0.11961551]
 [ 0.02963478]]

 W12: 
 [[ 0.97551768]
 [ 0.97551768]]

 W23: 
 [[ 0.50729551]
 [ 0.50729551]
 [ 0.00187866]]

 
 rodada 880 :

 gradW12: 
 [[-0.3884323]
 [-0.3884323]]

 gradW23: 
 [[ 0.11951714]
 [ 0.11951714]
 [ 0.02961225]]

 W12: 
 [[ 0.9755371]
 [ 0.9755371]]

 W23: 
 [[ 0.50728954]
 [ 0.50728954]
 [ 0.00187718]]

 
 rodada 881 :

 gradW12: 
 [[-0.3881328]
 [-0.3881328]]

 gradW23: 
 [[ 0.11941885]
 [ 0.11941885]
 [ 0.02958973]]

 W12: 
 [[ 0.9755565]
 [ 0.9755565]]

 W23: 
 [[ 0.50728357]
 [ 0.50728357]
 [ 0.0018757 ]]

 
 rodada 882 :

 gradW12: 
 [[-0.38783351]
 [-0.38783351]]

 gradW23: 
 [[ 0.11932065]
 [ 0.11932065]
 [ 0.02956723]]

 W12: 
 [[ 0.9755759]
 [ 0.975

 rodada 937 :

 gradW12: 
 [[-0.37170269]
 [-0.37170269]]

 gradW23: 
 [[ 0.11404248]
 [ 0.11404248]
 [ 0.02835367]]

 W12: 
 [[ 0.97661971]
 [ 0.97661971]]

 W23: 
 [[ 0.50695691]
 [ 0.50695691]
 [ 0.00179462]]

 
 rodada 938 :

 gradW12: 
 [[-0.37141533]
 [-0.37141533]]

 gradW23: 
 [[ 0.11394872]
 [ 0.11394872]
 [ 0.02833204]]

 W12: 
 [[ 0.97663828]
 [ 0.97663828]]

 W23: 
 [[ 0.50695121]
 [ 0.50695121]
 [ 0.0017932 ]]

 
 rodada 939 :

 gradW12: 
 [[-0.37112818]
 [-0.37112818]]

 gradW23: 
 [[ 0.11385503]
 [ 0.11385503]
 [ 0.02831042]]

 W12: 
 [[ 0.97665683]
 [ 0.97665683]]

 W23: 
 [[ 0.50694552]
 [ 0.50694552]
 [ 0.00179179]]

 
 rodada 940 :

 gradW12: 
 [[-0.37084124]
 [-0.37084124]]

 gradW23: 
 [[ 0.11376143]
 [ 0.11376143]
 [ 0.02828882]]

 W12: 
 [[ 0.97667538]
 [ 0.97667538]]

 W23: 
 [[ 0.50693983]
 [ 0.50693983]
 [ 0.00179037]]

 
 rodada 941 :

 gradW12: 
 [[-0.37055451]
 [-0.37055451]]

 gradW23: 
 [[ 0.1136679 ]
 [ 0.1136679 ]
 [ 0.02826723]]

 W12: 
 [[ 0.9766939]



 gradW23: 
 [[ 0.10864112]
 [ 0.10864112]
 [ 0.02710323]]

 W12: 
 [[ 0.97769115]
 [ 0.97769115]]

 W23: 
 [[ 0.50662865]
 [ 0.50662865]
 [ 0.00171286]]

 
 rodada 997 :

 gradW12: 
 [[-0.35482715]
 [-0.35482715]]

 gradW23: 
 [[ 0.10855182]
 [ 0.10855182]
 [ 0.02708249]]

 W12: 
 [[ 0.9777089]
 [ 0.9777089]]

 W23: 
 [[ 0.50662323]
 [ 0.50662323]
 [ 0.00171151]]

 
 rodada 998 :

 gradW12: 
 [[-0.35455212]
 [-0.35455212]]

 gradW23: 
 [[ 0.1084626 ]
 [ 0.1084626 ]
 [ 0.02706176]]

 W12: 
 [[ 0.97772662]
 [ 0.97772662]]

 W23: 
 [[ 0.5066178 ]
 [ 0.5066178 ]
 [ 0.00171016]]

 
 rodada 999 :

 gradW12: 
 [[-0.35427729]
 [-0.35427729]]

 gradW23: 
 [[ 0.10837345]
 [ 0.10837345]
 [ 0.02704104]]

 W12: 
 [[ 0.97774434]
 [ 0.97774434]]

 W23: 
 [[ 0.50661238]
 [ 0.50661238]
 [ 0.00170881]]

 
 rodada 1000 :

 gradW12: 
 [[-0.35400266]
 [-0.35400266]]

 gradW23: 
 [[ 0.10828437]
 [ 0.10828437]
 [ 0.02702034]]

 W12: 
 [[ 0.97776204]
 [ 0.97776204]]

 W23: 
 [[ 0.50660697]
 [ 0.50660697]
 [ 

 rodada 1058 :

 gradW12: 
 [[-0.33841432]
 [-0.33841432]]

 gradW23: 
 [[ 0.10324202]
 [ 0.10324202]
 [ 0.02584461]]

 W12: 
 [[ 0.97876549]
 [ 0.97876549]]

 W23: 
 [[ 0.50630044]
 [ 0.50630044]
 [ 0.00163084]]

 
 rodada 1059 :

 gradW12: 
 [[-0.33815134]
 [-0.33815134]]

 gradW23: 
 [[ 0.10315719]
 [ 0.10315719]
 [ 0.02582477]]

 W12: 
 [[ 0.9787824]
 [ 0.9787824]]

 W23: 
 [[ 0.50629528]
 [ 0.50629528]
 [ 0.00162955]]

 
 rodada 1060 :

 gradW12: 
 [[-0.33788856]
 [-0.33788856]]

 gradW23: 
 [[ 0.10307242]
 [ 0.10307242]
 [ 0.02580493]]

 W12: 
 [[ 0.97879929]
 [ 0.97879929]]

 W23: 
 [[ 0.50629013]
 [ 0.50629013]
 [ 0.00162826]]

 
 rodada 1061 :

 gradW12: 
 [[-0.33762598]
 [-0.33762598]]

 gradW23: 
 [[ 0.10298773]
 [ 0.10298773]
 [ 0.02578512]]

 W12: 
 [[ 0.97881617]
 [ 0.97881617]]

 W23: 
 [[ 0.50628498]
 [ 0.50628498]
 [ 0.00162697]]

 
 rodada 1062 :

 gradW12: 
 [[-0.33736358]
 [-0.33736358]]

 gradW23: 
 [[ 0.1029031 ]
 [ 0.1029031 ]
 [ 0.02576531]]

 W12: 
 [[ 0.978833

 rodada 1119 :

 gradW12: 
 [[-0.32272299]
 [-0.32272299]]

 gradW23: 
 [[ 0.09819334]
 [ 0.09819334]
 [ 0.02465973]]

 W12: 
 [[ 0.97977315]
 [ 0.97977315]]

 W23: 
 [[ 0.50599344]
 [ 0.50599344]
 [ 0.00155387]]

 
 rodada 1120 :

 gradW12: 
 [[-0.32247161]
 [-0.32247161]]

 gradW23: 
 [[ 0.09811267]
 [ 0.09811267]
 [ 0.02464074]]

 W12: 
 [[ 0.97978928]
 [ 0.97978928]]

 W23: 
 [[ 0.50598854]
 [ 0.50598854]
 [ 0.00155263]]

 
 rodada 1121 :

 gradW12: 
 [[-0.32222041]
 [-0.32222041]]

 gradW23: 
 [[ 0.09803208]
 [ 0.09803208]
 [ 0.02462176]]

 W12: 
 [[ 0.97980539]
 [ 0.97980539]]

 W23: 
 [[ 0.50598364]
 [ 0.50598364]
 [ 0.0015514 ]]

 
 rodada 1122 :

 gradW12: 
 [[-0.3219694]
 [-0.3219694]]

 gradW23: 
 [[ 0.09795155]
 [ 0.09795155]
 [ 0.02460279]]

 W12: 
 [[ 0.97982149]
 [ 0.97982149]]

 W23: 
 [[ 0.50597874]
 [ 0.50597874]
 [ 0.00155017]]

 
 rodada 1123 :

 gradW12: 
 [[-0.32171858]
 [-0.32171858]]

 gradW23: 
 [[ 0.09787108]
 [ 0.09787108]
 [ 0.02458384]]

 W12: 
 [[ 0.979837

 rodada 1180 :

 gradW12: 
 [[-0.30772508]
 [-0.30772508]]

 gradW23: 
 [[ 0.09339285]
 [ 0.09339285]
 [ 0.02352593]]

 W12: 
 [[ 0.98073404]
 [ 0.98073404]]

 W23: 
 [[ 0.50570146]
 [ 0.50570146]
 [ 0.00148042]]

 
 rodada 1181 :

 gradW12: 
 [[-0.30748484]
 [-0.30748484]]

 gradW23: 
 [[ 0.09331616]
 [ 0.09331616]
 [ 0.02350776]]

 W12: 
 [[ 0.98074941]
 [ 0.98074941]]

 W23: 
 [[ 0.50569679]
 [ 0.50569679]
 [ 0.00147925]]

 
 rodada 1182 :

 gradW12: 
 [[-0.30724477]
 [-0.30724477]]

 gradW23: 
 [[ 0.09323952]
 [ 0.09323952]
 [ 0.0234896 ]]

 W12: 
 [[ 0.98076478]
 [ 0.98076478]]

 W23: 
 [[ 0.50569213]
 [ 0.50569213]
 [ 0.00147807]]

 
 rodada 1183 :

 gradW12: 
 [[-0.30700489]
 [-0.30700489]]

 gradW23: 
 [[ 0.09316295]
 [ 0.09316295]
 [ 0.02347145]]

 W12: 
 [[ 0.98078013]
 [ 0.98078013]]

 W23: 
 [[ 0.50568747]
 [ 0.50568747]
 [ 0.0014769 ]]

 
 rodada 1184 :

 gradW12: 
 [[-0.30676518]
 [-0.30676518]]

 gradW23: 
 [[ 0.09308644]
 [ 0.09308644]
 [ 0.02345332]]

 W12: 
 [[ 0.9807


 
 rodada 1244 :

 gradW12: 
 [[-0.29270512]
 [-0.29270512]]

 gradW23: 
 [[ 0.08860969]
 [ 0.08860969]
 [ 0.02238921]]

 W12: 
 [[ 0.98169416]
 [ 0.98169416]]

 W23: 
 [[ 0.50541044]
 [ 0.50541044]
 [ 0.001407  ]]

 
 rodada 1245 :

 gradW12: 
 [[-0.29247609]
 [-0.29247609]]

 gradW23: 
 [[ 0.08853694]
 [ 0.08853694]
 [ 0.02237187]]

 W12: 
 [[ 0.98170878]
 [ 0.98170878]]

 W23: 
 [[ 0.50540601]
 [ 0.50540601]
 [ 0.00140588]]

 
 rodada 1246 :

 gradW12: 
 [[-0.29224722]
 [-0.29224722]]

 gradW23: 
 [[ 0.08846425]
 [ 0.08846425]
 [ 0.02235453]]

 W12: 
 [[ 0.9817234]
 [ 0.9817234]]

 W23: 
 [[ 0.50540159]
 [ 0.50540159]
 [ 0.00140477]]

 
 rodada 1247 :

 gradW12: 
 [[-0.29201853]
 [-0.29201853]]

 gradW23: 
 [[ 0.08839162]
 [ 0.08839162]
 [ 0.02233722]]

 W12: 
 [[ 0.981738]
 [ 0.981738]]

 W23: 
 [[ 0.50539717]
 [ 0.50539717]
 [ 0.00140365]]

 
 rodada 1248 :

 gradW12: 
 [[-0.29179001]
 [-0.29179001]]

 gradW23: 
 [[ 0.08831905]
 [ 0.08831905]
 [ 0.02231991]]

 W12: 
 [[ 0.9817525


 
 rodada 1305 :

 gradW12: 
 [[-0.27904354]
 [-0.27904354]]

 gradW23: 
 [[ 0.08428012]
 [ 0.08428012]
 [ 0.02135421]]

 W12: 
 [[ 0.98256558]
 [ 0.98256558]]

 W23: 
 [[ 0.50514695]
 [ 0.50514695]
 [ 0.00134033]]

 
 rodada 1306 :

 gradW12: 
 [[-0.27882475]
 [-0.27882475]]

 gradW23: 
 [[ 0.08421094]
 [ 0.08421094]
 [ 0.02133763]]

 W12: 
 [[ 0.98257952]
 [ 0.98257952]]

 W23: 
 [[ 0.50514273]
 [ 0.50514273]
 [ 0.00133926]]

 
 rodada 1307 :

 gradW12: 
 [[-0.27860613]
 [-0.27860613]]

 gradW23: 
 [[ 0.08414182]
 [ 0.08414182]
 [ 0.02132106]]

 W12: 
 [[ 0.98259345]
 [ 0.98259345]]

 W23: 
 [[ 0.50513853]
 [ 0.50513853]
 [ 0.0013382 ]]

 
 rodada 1308 :

 gradW12: 
 [[-0.27838767]
 [-0.27838767]]

 gradW23: 
 [[ 0.08407276]
 [ 0.08407276]
 [ 0.0213045 ]]

 W12: 
 [[ 0.98260737]
 [ 0.98260737]]

 W23: 
 [[ 0.50513432]
 [ 0.50513432]
 [ 0.00133713]]

 
 rodada 1309 :

 gradW12: 
 [[-0.27816937]
 [-0.27816937]]

 gradW23: 
 [[ 0.08400376]
 [ 0.08400376]
 [ 0.02128795]]

 W12: 
 [[ 0.9


 
 rodada 1355 :

 gradW12: 
 [[-0.26830336]
 [-0.26830336]]

 gradW23: 
 [[ 0.08089034]
 [ 0.08089034]
 [ 0.02053982]]

 W12: 
 [[ 0.98324941]
 [ 0.98324941]]

 W23: 
 [[ 0.5049406 ]
 [ 0.5049406 ]
 [ 0.00128799]]

 
 rodada 1356 :

 gradW12: 
 [[-0.26809266]
 [-0.26809266]]

 gradW23: 
 [[ 0.08082396]
 [ 0.08082396]
 [ 0.02052384]]

 W12: 
 [[ 0.98326281]
 [ 0.98326281]]

 W23: 
 [[ 0.50493655]
 [ 0.50493655]
 [ 0.00128696]]

 
 rodada 1357 :

 gradW12: 
 [[-0.26788212]
 [-0.26788212]]

 gradW23: 
 [[ 0.08075764]
 [ 0.08075764]
 [ 0.02050787]]

 W12: 
 [[ 0.98327621]
 [ 0.98327621]]

 W23: 
 [[ 0.50493252]
 [ 0.50493252]
 [ 0.00128594]]

 
 rodada 1358 :

 gradW12: 
 [[-0.26767173]
 [-0.26767173]]

 gradW23: 
 [[ 0.08069137]
 [ 0.08069137]
 [ 0.02049191]]

 W12: 
 [[ 0.98328959]
 [ 0.98328959]]

 W23: 
 [[ 0.50492848]
 [ 0.50492848]
 [ 0.00128491]]

 
 rodada 1359 :

 gradW12: 
 [[-0.26746151]
 [-0.26746151]]

 gradW23: 
 [[ 0.08062515]
 [ 0.08062515]
 [ 0.02047596]]

 W12: 
 [[ 0.9

 [[ 0.98388109]
 [ 0.98388109]]

 W23: 
 [[ 0.50475031]
 [ 0.50475031]
 [ 0.00123962]]

 
 rodada 1404 :

 gradW12: 
 [[-0.25816383]
 [-0.25816383]]

 gradW23: 
 [[ 0.07770135]
 [ 0.07770135]
 [ 0.01977041]]

 W12: 
 [[ 0.983894]
 [ 0.983894]]

 W23: 
 [[ 0.50474643]
 [ 0.50474643]
 [ 0.00123863]]

 
 rodada 1405 :

 gradW12: 
 [[-0.25796079]
 [-0.25796079]]

 gradW23: 
 [[ 0.0776376 ]
 [ 0.0776376 ]
 [ 0.01975499]]

 W12: 
 [[ 0.9839069]
 [ 0.9839069]]

 W23: 
 [[ 0.50474255]
 [ 0.50474255]
 [ 0.00123765]]

 
 rodada 1406 :

 gradW12: 
 [[-0.2577579]
 [-0.2577579]]

 gradW23: 
 [[ 0.0775739 ]
 [ 0.0775739 ]
 [ 0.01973959]]

 W12: 
 [[ 0.98391979]
 [ 0.98391979]]

 W23: 
 [[ 0.50473867]
 [ 0.50473867]
 [ 0.00123666]]

 
 rodada 1407 :

 gradW12: 
 [[-0.25755517]
 [-0.25755517]]

 gradW23: 
 [[ 0.07751026]
 [ 0.07751026]
 [ 0.0197242 ]]

 W12: 
 [[ 0.98393266]
 [ 0.98393266]]

 W23: 
 [[ 0.50473479]
 [ 0.50473479]
 [ 0.00123567]]

 
 rodada 1408 :

 gradW12: 
 [[-0.25735259]
 [-0.257352


 
 rodada 1455 :

 gradW12: 
 [[-0.24800237]
 [-0.24800237]]

 gradW23: 
 [[ 0.07451631]
 [ 0.07451631]
 [ 0.01899876]]

 W12: 
 [[ 0.98453902]
 [ 0.98453902]]

 W23: 
 [[ 0.50455246]
 [ 0.50455246]
 [ 0.00118923]]

 
 rodada 1456 :

 gradW12: 
 [[-0.24780702]
 [-0.24780702]]

 gradW23: 
 [[ 0.07445519]
 [ 0.07445519]
 [ 0.01898392]]

 W12: 
 [[ 0.98455141]
 [ 0.98455141]]

 W23: 
 [[ 0.50454873]
 [ 0.50454873]
 [ 0.00118828]]

 
 rodada 1457 :

 gradW12: 
 [[-0.24761183]
 [-0.24761183]]

 gradW23: 
 [[ 0.07439411]
 [ 0.07439411]
 [ 0.0189691 ]]

 W12: 
 [[ 0.9845638]
 [ 0.9845638]]

 W23: 
 [[ 0.50454502]
 [ 0.50454502]
 [ 0.00118733]]

 
 rodada 1458 :

 gradW12: 
 [[-0.24741679]
 [-0.24741679]]

 gradW23: 
 [[ 0.07433309]
 [ 0.07433309]
 [ 0.01895428]]

 W12: 
 [[ 0.98457617]
 [ 0.98457617]]

 W23: 
 [[ 0.5045413 ]
 [ 0.5045413 ]
 [ 0.00118638]]

 
 rodada 1459 :

 gradW12: 
 [[-0.24722189]
 [-0.24722189]]

 gradW23: 
 [[ 0.07427212]
 [ 0.07427212]
 [ 0.01893947]]

 W12: 
 [[ 0.984


 
 rodada 1517 :

 gradW12: 
 [[-0.23616778]
 [-0.23616778]]

 gradW23: 
 [[ 0.07082047]
 [ 0.07082047]
 [ 0.01809937]]

 W12: 
 [[ 0.98528905]
 [ 0.98528905]]

 W23: 
 [[ 0.50432733]
 [ 0.50432733]
 [ 0.00113176]]

 
 rodada 1518 :

 gradW12: 
 [[-0.23598144]
 [-0.23598144]]

 gradW23: 
 [[ 0.07076239]
 [ 0.07076239]
 [ 0.0180852 ]]

 W12: 
 [[ 0.98530085]
 [ 0.98530085]]

 W23: 
 [[ 0.50432379]
 [ 0.50432379]
 [ 0.00113086]]

 
 rodada 1519 :

 gradW12: 
 [[-0.23579524]
 [-0.23579524]]

 gradW23: 
 [[ 0.07070437]
 [ 0.07070437]
 [ 0.01807104]]

 W12: 
 [[ 0.98531264]
 [ 0.98531264]]

 W23: 
 [[ 0.50432025]
 [ 0.50432025]
 [ 0.00112995]]

 
 rodada 1520 :

 gradW12: 
 [[-0.23560919]
 [-0.23560919]]

 gradW23: 
 [[ 0.07064639]
 [ 0.07064639]
 [ 0.0180569 ]]

 W12: 
 [[ 0.98532442]
 [ 0.98532442]]

 W23: 
 [[ 0.50431672]
 [ 0.50431672]
 [ 0.00112905]]

 
 rodada 1521 :

 gradW12: 
 [[-0.23542327]
 [-0.23542327]]

 gradW23: 
 [[ 0.07058845]
 [ 0.07058845]
 [ 0.01804276]]

 W12: 
 [[ 0.9

 rodada 1580 :

 gradW12: 
 [[-0.22470175]
 [-0.22470175]]

 gradW23: 
 [[ 0.06725363]
 [ 0.06725363]
 [ 0.01722727]]

 W12: 
 [[ 0.98601449]
 [ 0.98601449]]

 W23: 
 [[ 0.50411   ]
 [ 0.50411   ]
 [ 0.00107615]]

 
 rodada 1581 :

 gradW12: 
 [[-0.22452416]
 [-0.22452416]]

 gradW23: 
 [[ 0.06719849]
 [ 0.06719849]
 [ 0.01721375]]

 W12: 
 [[ 0.98602571]
 [ 0.98602571]]

 W23: 
 [[ 0.50410664]
 [ 0.50410664]
 [ 0.00107529]]

 
 rodada 1582 :

 gradW12: 
 [[-0.22434671]
 [-0.22434671]]

 gradW23: 
 [[ 0.0671434 ]
 [ 0.0671434 ]
 [ 0.01720025]]

 W12: 
 [[ 0.98603693]
 [ 0.98603693]]

 W23: 
 [[ 0.50410328]
 [ 0.50410328]
 [ 0.00107443]]

 
 rodada 1583 :

 gradW12: 
 [[-0.2241694]
 [-0.2241694]]

 gradW23: 
 [[ 0.06708835]
 [ 0.06708835]
 [ 0.01718676]]

 W12: 
 [[ 0.98604814]
 [ 0.98604814]]

 W23: 
 [[ 0.50409993]
 [ 0.50409993]
 [ 0.00107357]]

 
 rodada 1584 :

 gradW12: 
 [[-0.22399222]
 [-0.22399222]]

 gradW23: 
 [[ 0.06703335]
 [ 0.06703335]
 [ 0.01717328]]

 W12: 
 [[ 0.986059

 rodada 1629 :

 gradW12: 
 [[-0.21615793]
 [-0.21615793]]

 gradW23: 
 [[ 0.06460467]
 [ 0.06460467]
 [ 0.01657697]]

 W12: 
 [[ 0.98655426]
 [ 0.98655426]]

 W23: 
 [[ 0.50394856]
 [ 0.50394856]
 [ 0.00103476]]

 
 rodada 1630 :

 gradW12: 
 [[-0.21598689]
 [-0.21598689]]

 gradW23: 
 [[ 0.06455171]
 [ 0.06455171]
 [ 0.01656395]]

 W12: 
 [[ 0.98656506]
 [ 0.98656506]]

 W23: 
 [[ 0.50394533]
 [ 0.50394533]
 [ 0.00103394]]

 
 rodada 1631 :

 gradW12: 
 [[-0.21581597]
 [-0.21581597]]

 gradW23: 
 [[ 0.0644988 ]
 [ 0.0644988 ]
 [ 0.01655094]]

 W12: 
 [[ 0.98657585]
 [ 0.98657585]]

 W23: 
 [[ 0.50394211]
 [ 0.50394211]
 [ 0.00103311]]

 
 rodada 1632 :

 gradW12: 
 [[-0.21564519]
 [-0.21564519]]

 gradW23: 
 [[ 0.06444593]
 [ 0.06444593]
 [ 0.01653793]]

 W12: 
 [[ 0.98658663]
 [ 0.98658663]]

 W23: 
 [[ 0.50393888]
 [ 0.50393888]
 [ 0.00103228]]

 
 rodada 1633 :

 gradW12: 
 [[-0.21547454]
 [-0.21547454]]

 gradW23: 
 [[ 0.06439311]
 [ 0.06439311]
 [ 0.01652494]]

 W12: 
 [[ 0.9865

 [[-0.20645127]
 [-0.20645127]]

 gradW23: 
 [[ 0.06160429]
 [ 0.06160429]
 [ 0.0158377 ]]

 W12: 
 [[ 0.9871667]
 [ 0.9871667]]

 W23: 
 [[ 0.50376567]
 [ 0.50376567]
 [ 0.00098779]]

 
 rodada 1688 :

 gradW12: 
 [[-0.20628768]
 [-0.20628768]]

 gradW23: 
 [[ 0.06155381]
 [ 0.06155381]
 [ 0.01582524]]

 W12: 
 [[ 0.98717701]
 [ 0.98717701]]

 W23: 
 [[ 0.50376259]
 [ 0.50376259]
 [ 0.000987  ]]

 
 rodada 1689 :

 gradW12: 
 [[-0.20612421]
 [-0.20612421]]

 gradW23: 
 [[ 0.06150337]
 [ 0.06150337]
 [ 0.01581278]]

 W12: 
 [[ 0.98718732]
 [ 0.98718732]]

 W23: 
 [[ 0.50375951]
 [ 0.50375951]
 [ 0.00098621]]

 
 rodada 1690 :

 gradW12: 
 [[-0.20596087]
 [-0.20596087]]

 gradW23: 
 [[ 0.06145297]
 [ 0.06145297]
 [ 0.01580034]]

 W12: 
 [[ 0.98719762]
 [ 0.98719762]]

 W23: 
 [[ 0.50375644]
 [ 0.50375644]
 [ 0.00098542]]

 
 rodada 1691 :

 gradW12: 
 [[-0.20579766]
 [-0.20579766]]

 gradW23: 
 [[ 0.06140261]
 [ 0.06140261]
 [ 0.0157879 ]]

 W12: 
 [[ 0.98720791]
 [ 0.98720791]]

 W23: 

 [[ 0.98780079]
 [ 0.98780079]]

 W23: 
 [[ 0.50357662]
 [ 0.50357662]
 [ 0.00093914]]

 
 rodada 1751 :

 gradW12: 
 [[-0.19623135]
 [-0.19623135]]

 gradW23: 
 [[ 0.0584557]
 [ 0.0584557]
 [ 0.0150588]]

 W12: 
 [[ 0.9878106]
 [ 0.9878106]]

 W23: 
 [[ 0.50357369]
 [ 0.50357369]
 [ 0.00093838]]

 
 rodada 1752 :

 gradW12: 
 [[-0.19607563]
 [-0.19607563]]

 gradW23: 
 [[ 0.05840781]
 [ 0.05840781]
 [ 0.01504693]]

 W12: 
 [[ 0.9878204]
 [ 0.9878204]]

 W23: 
 [[ 0.50357077]
 [ 0.50357077]
 [ 0.00093763]]

 
 rodada 1753 :

 gradW12: 
 [[-0.19592003]
 [-0.19592003]]

 gradW23: 
 [[ 0.05835995]
 [ 0.05835995]
 [ 0.01503507]]

 W12: 
 [[ 0.9878302]
 [ 0.9878302]]

 W23: 
 [[ 0.50356785]
 [ 0.50356785]
 [ 0.00093688]]

 
 rodada 1754 :

 gradW12: 
 [[-0.19576455]
 [-0.19576455]]

 gradW23: 
 [[ 0.05831214]
 [ 0.05831214]
 [ 0.01502321]]

 W12: 
 [[ 0.98783999]
 [ 0.98783999]]

 W23: 
 [[ 0.50356494]
 [ 0.50356494]
 [ 0.00093613]]

 
 rodada 1755 :

 gradW12: 
 [[-0.19560919]
 [-0.1956091

 [[-0.18874079]
 [-0.18874079]]

 gradW23: 
 [[ 0.05615474]
 [ 0.05615474]
 [ 0.01448757]]

 W12: 
 [[ 0.98828194]
 [ 0.98828194]]

 W23: 
 [[ 0.50343337]
 [ 0.50343337]
 [ 0.00090221]]

 
 rodada 1801 :

 gradW12: 
 [[-0.18859086]
 [-0.18859086]]

 gradW23: 
 [[ 0.05610874]
 [ 0.05610874]
 [ 0.01447613]]

 W12: 
 [[ 0.98829137]
 [ 0.98829137]]

 W23: 
 [[ 0.50343057]
 [ 0.50343057]
 [ 0.00090149]]

 
 rodada 1802 :

 gradW12: 
 [[-0.18844104]
 [-0.18844104]]

 gradW23: 
 [[ 0.05606278]
 [ 0.05606278]
 [ 0.0144647 ]]

 W12: 
 [[ 0.9883008]
 [ 0.9883008]]

 W23: 
 [[ 0.50342776]
 [ 0.50342776]
 [ 0.00090076]]

 
 rodada 1803 :

 gradW12: 
 [[-0.18829134]
 [-0.18829134]]

 gradW23: 
 [[ 0.05601686]
 [ 0.05601686]
 [ 0.01445329]]

 W12: 
 [[ 0.98831021]
 [ 0.98831021]]

 W23: 
 [[ 0.50342496]
 [ 0.50342496]
 [ 0.00090004]]

 
 rodada 1804 :

 gradW12: 
 [[-0.18814175]
 [-0.18814175]]

 gradW23: 
 [[ 0.05597097]
 [ 0.05597097]
 [ 0.01444187]]

 W12: 
 [[ 0.98831962]
 [ 0.98831962]]

 W23: 

 rodada 1856 :

 gradW12: 
 [[-0.1805207]
 [-0.1805207]]

 gradW23: 
 [[ 0.05363623]
 [ 0.05363623]
 [ 0.01386037]]

 W12: 
 [[ 0.98879862]
 [ 0.98879862]]

 W23: 
 [[ 0.50327975]
 [ 0.50327975]
 [ 0.00086254]]

 
 rodada 1857 :

 gradW12: 
 [[-0.18037713]
 [-0.18037713]]

 gradW23: 
 [[ 0.0535923 ]
 [ 0.0535923 ]
 [ 0.01384941]]

 W12: 
 [[ 0.98880764]
 [ 0.98880764]]

 W23: 
 [[ 0.50327708]
 [ 0.50327708]
 [ 0.00086185]]

 
 rodada 1858 :

 gradW12: 
 [[-0.18023367]
 [-0.18023367]]

 gradW23: 
 [[ 0.05354841]
 [ 0.05354841]
 [ 0.01383846]]

 W12: 
 [[ 0.98881665]
 [ 0.98881665]]

 W23: 
 [[ 0.5032744 ]
 [ 0.5032744 ]
 [ 0.00086116]]

 
 rodada 1859 :

 gradW12: 
 [[-0.18009032]
 [-0.18009032]]

 gradW23: 
 [[ 0.05350456]
 [ 0.05350456]
 [ 0.01382752]]

 W12: 
 [[ 0.98882566]
 [ 0.98882566]]

 W23: 
 [[ 0.50327172]
 [ 0.50327172]
 [ 0.00086047]]

 
 rodada 1860 :

 gradW12: 
 [[-0.17994708]
 [-0.17994708]]

 gradW23: 
 [[ 0.05346074]
 [ 0.05346074]
 [ 0.01381658]]

 W12: 
 [[ 0.988834


 
 rodada 1910 :

 gradW12: 
 [[-0.17292513]
 [-0.17292513]]

 gradW23: 
 [[ 0.05131514]
 [ 0.05131514]
 [ 0.0132805 ]]

 W12: 
 [[ 0.98927551]
 [ 0.98927551]]

 W23: 
 [[ 0.50313815]
 [ 0.50313815]
 [ 0.00082592]]

 
 rodada 1911 :

 gradW12: 
 [[-0.17278746]
 [-0.17278746]]

 gradW23: 
 [[ 0.05127312]
 [ 0.05127312]
 [ 0.01326999]]

 W12: 
 [[ 0.98928415]
 [ 0.98928415]]

 W23: 
 [[ 0.50313559]
 [ 0.50313559]
 [ 0.00082526]]

 
 rodada 1912 :

 gradW12: 
 [[-0.17264989]
 [-0.17264989]]

 gradW23: 
 [[ 0.05123114]
 [ 0.05123114]
 [ 0.01325948]]

 W12: 
 [[ 0.98929278]
 [ 0.98929278]]

 W23: 
 [[ 0.50313303]
 [ 0.50313303]
 [ 0.0008246 ]]

 
 rodada 1913 :

 gradW12: 
 [[-0.17251242]
 [-0.17251242]]

 gradW23: 
 [[ 0.05118919]
 [ 0.05118919]
 [ 0.01324898]]

 W12: 
 [[ 0.98930141]
 [ 0.98930141]]

 W23: 
 [[ 0.50313047]
 [ 0.50313047]
 [ 0.00082393]]

 
 rodada 1914 :

 gradW12: 
 [[-0.17237507]
 [-0.17237507]]

 gradW23: 
 [[ 0.05114727]
 [ 0.05114727]
 [ 0.0132385 ]]

 W12: 
 [[ 0.9

 [ 0.01270402]]

 W12: 
 [[ 0.98974887]
 [ 0.98974887]]

 W23: 
 [[ 0.50299777]
 [ 0.50299777]
 [ 0.00078957]]

 
 rodada 1967 :

 gradW12: 
 [[-0.16524599]
 [-0.16524599]]

 gradW23: 
 [[ 0.04897441]
 [ 0.04897441]
 [ 0.01269395]]

 W12: 
 [[ 0.98975713]
 [ 0.98975713]]

 W23: 
 [[ 0.50299532]
 [ 0.50299532]
 [ 0.00078893]]

 
 rodada 1968 :

 gradW12: 
 [[-0.16511429]
 [-0.16511429]]

 gradW23: 
 [[ 0.04893432]
 [ 0.04893432]
 [ 0.01268389]]

 W12: 
 [[ 0.98976539]
 [ 0.98976539]]

 W23: 
 [[ 0.50299288]
 [ 0.50299288]
 [ 0.0007883 ]]

 
 rodada 1969 :

 gradW12: 
 [[-0.16498269]
 [-0.16498269]]

 gradW23: 
 [[ 0.04889426]
 [ 0.04889426]
 [ 0.01267383]]

 W12: 
 [[ 0.98977364]
 [ 0.98977364]]

 W23: 
 [[ 0.50299043]
 [ 0.50299043]
 [ 0.00078766]]

 
 rodada 1970 :

 gradW12: 
 [[-0.16485119]
 [-0.16485119]]

 gradW23: 
 [[ 0.04885423]
 [ 0.04885423]
 [ 0.01266379]]

 W12: 
 [[ 0.98978188]
 [ 0.98978188]]

 W23: 
 [[ 0.50298799]
 [ 0.50298799]
 [ 0.00078703]]

 
 rodada 1971 :

 gradW

 [[-0.15853169]
 [-0.15853169]]

 gradW23: 
 [[ 0.04693263]
 [ 0.04693263]
 [ 0.01218085]]

 W12: 
 [[ 0.99017782]
 [ 0.99017782]]

 W23: 
 [[ 0.50287071]
 [ 0.50287071]
 [ 0.00075661]]

 
 rodada 2020 :

 gradW12: 
 [[-0.15840522]
 [-0.15840522]]

 gradW23: 
 [[ 0.04689422]
 [ 0.04689422]
 [ 0.01217118]]

 W12: 
 [[ 0.99018574]
 [ 0.99018574]]

 W23: 
 [[ 0.50286837]
 [ 0.50286837]
 [ 0.000756  ]]

 
 rodada 2021 :

 gradW12: 
 [[-0.15827885]
 [-0.15827885]]

 gradW23: 
 [[ 0.04685583]
 [ 0.04685583]
 [ 0.01216152]]

 W12: 
 [[ 0.99019365]
 [ 0.99019365]]

 W23: 
 [[ 0.50286603]
 [ 0.50286603]
 [ 0.00075539]]

 
 rodada 2022 :

 gradW12: 
 [[-0.15815258]
 [-0.15815258]]

 gradW23: 
 [[ 0.04681748]
 [ 0.04681748]
 [ 0.01215187]]

 W12: 
 [[ 0.99020156]
 [ 0.99020156]]

 W23: 
 [[ 0.50286369]
 [ 0.50286369]
 [ 0.00075479]]

 
 rodada 2023 :

 gradW12: 
 [[-0.1580264]
 [-0.1580264]]

 gradW23: 
 [[ 0.04677916]
 [ 0.04677916]
 [ 0.01214222]]

 W12: 
 [[ 0.99020946]
 [ 0.99020946]]

 W23: 


 gradW12: 
 [[-0.15342651]
 [-0.15342651]]

 gradW23: 
 [[ 0.04538319]
 [ 0.04538319]
 [ 0.01179056]]

 W12: 
 [[ 0.99049742]
 [ 0.99049742]]

 W23: 
 [[ 0.50277614]
 [ 0.50277614]
 [ 0.00073205]]

 
 rodada 2061 :

 gradW12: 
 [[-0.15330403]
 [-0.15330403]]

 gradW23: 
 [[ 0.04534605]
 [ 0.04534605]
 [ 0.01178119]]

 W12: 
 [[ 0.99050508]
 [ 0.99050508]]

 W23: 
 [[ 0.50277387]
 [ 0.50277387]
 [ 0.00073146]]

 
 rodada 2062 :

 gradW12: 
 [[-0.15318164]
 [-0.15318164]]

 gradW23: 
 [[ 0.04530894]
 [ 0.04530894]
 [ 0.01177183]]

 W12: 
 [[ 0.99051274]
 [ 0.99051274]]

 W23: 
 [[ 0.50277161]
 [ 0.50277161]
 [ 0.00073087]]

 
 rodada 2063 :

 gradW12: 
 [[-0.15305935]
 [-0.15305935]]

 gradW23: 
 [[ 0.04527185]
 [ 0.04527185]
 [ 0.01176248]]

 W12: 
 [[ 0.9905204]
 [ 0.9905204]]

 W23: 
 [[ 0.50276934]
 [ 0.50276934]
 [ 0.00073029]]

 
 rodada 2064 :

 gradW12: 
 [[-0.15293715]
 [-0.15293715]]

 gradW23: 
 [[ 0.0452348 ]
 [ 0.0452348 ]
 [ 0.01175314]]

 W12: 
 [[ 0.99052804]
 [ 0.990528

 rodada 2115 :

 gradW12: 
 [[-0.14683009]
 [-0.14683009]]

 gradW23: 
 [[ 0.043385  ]
 [ 0.043385  ]
 [ 0.01128606]]

 W12: 
 [[ 0.99091004]
 [ 0.99091004]]

 W23: 
 [[ 0.50265415]
 [ 0.50265415]
 [ 0.00070034]]

 
 rodada 2116 :

 gradW12: 
 [[-0.14671277]
 [-0.14671277]]

 gradW23: 
 [[ 0.0433495 ]
 [ 0.0433495 ]
 [ 0.01127709]]

 W12: 
 [[ 0.99091738]
 [ 0.99091738]]

 W23: 
 [[ 0.50265199]
 [ 0.50265199]
 [ 0.00069978]]

 
 rodada 2117 :

 gradW12: 
 [[-0.14659553]
 [-0.14659553]]

 gradW23: 
 [[ 0.04331402]
 [ 0.04331402]
 [ 0.01126812]]

 W12: 
 [[ 0.99092471]
 [ 0.99092471]]

 W23: 
 [[ 0.50264982]
 [ 0.50264982]
 [ 0.00069921]]

 
 rodada 2118 :

 gradW12: 
 [[-0.14647839]
 [-0.14647839]]

 gradW23: 
 [[ 0.04327858]
 [ 0.04327858]
 [ 0.01125916]]

 W12: 
 [[ 0.99093203]
 [ 0.99093203]]

 W23: 
 [[ 0.50264766]
 [ 0.50264766]
 [ 0.00069865]]

 
 rodada 2119 :

 gradW12: 
 [[-0.14636134]
 [-0.14636134]]

 gradW23: 
 [[ 0.04324317]
 [ 0.04324317]
 [ 0.0112502 ]]

 W12: 
 [[ 0.9909


 
 rodada 2163 :

 gradW12: 
 [[-0.14130086]
 [-0.14130086]]

 gradW23: 
 [[ 0.04171341]
 [ 0.04171341]
 [ 0.01086301]]

 W12: 
 [[ 0.99125562]
 [ 0.99125562]]

 W23: 
 [[ 0.50255209]
 [ 0.50255209]
 [ 0.00067377]]

 
 rodada 2164 :

 gradW12: 
 [[-0.14118786]
 [-0.14118786]]

 gradW23: 
 [[ 0.04167928]
 [ 0.04167928]
 [ 0.01085437]]

 W12: 
 [[ 0.99126268]
 [ 0.99126268]]

 W23: 
 [[ 0.50255001]
 [ 0.50255001]
 [ 0.00067323]]

 
 rodada 2165 :

 gradW12: 
 [[-0.14107496]
 [-0.14107496]]

 gradW23: 
 [[ 0.04164518]
 [ 0.04164518]
 [ 0.01084573]]

 W12: 
 [[ 0.99126973]
 [ 0.99126973]]

 W23: 
 [[ 0.50254792]
 [ 0.50254792]
 [ 0.00067269]]

 
 rodada 2166 :

 gradW12: 
 [[-0.14096214]
 [-0.14096214]]

 gradW23: 
 [[ 0.04161111]
 [ 0.04161111]
 [ 0.01083709]]

 W12: 
 [[ 0.99127678]
 [ 0.99127678]]

 W23: 
 [[ 0.50254584]
 [ 0.50254584]
 [ 0.00067215]]

 
 rodada 2167 :

 gradW12: 
 [[-0.14084941]
 [-0.14084941]]

 gradW23: 
 [[ 0.04157706]
 [ 0.04157706]
 [ 0.01082847]]

 W12: 
 [[ 0.9

 [[ 0.04004085]
 [ 0.04004085]
 [ 0.0104388 ]]

 W12: 
 [[ 0.99160176]
 [ 0.99160176]]

 W23: 
 [[ 0.50244995]
 [ 0.50244995]
 [ 0.00064716]]

 
 rodada 2214 :

 gradW12: 
 [[-0.13564973]
 [-0.13564973]]

 gradW23: 
 [[ 0.0400081 ]
 [ 0.0400081 ]
 [ 0.01043048]]

 W12: 
 [[ 0.99160854]
 [ 0.99160854]]

 W23: 
 [[ 0.50244795]
 [ 0.50244795]
 [ 0.00064664]]

 
 rodada 2215 :

 gradW12: 
 [[-0.13554117]
 [-0.13554117]]

 gradW23: 
 [[ 0.03997537]
 [ 0.03997537]
 [ 0.01042217]]

 W12: 
 [[ 0.99161532]
 [ 0.99161532]]

 W23: 
 [[ 0.50244595]
 [ 0.50244595]
 [ 0.00064612]]

 
 rodada 2216 :

 gradW12: 
 [[-0.1354327]
 [-0.1354327]]

 gradW23: 
 [[ 0.03994267]
 [ 0.03994267]
 [ 0.01041386]]

 W12: 
 [[ 0.99162209]
 [ 0.99162209]]

 W23: 
 [[ 0.50244396]
 [ 0.50244396]
 [ 0.0006456 ]]

 
 rodada 2217 :

 gradW12: 
 [[-0.13532431]
 [-0.13532431]]

 gradW23: 
 [[ 0.03990999]
 [ 0.03990999]
 [ 0.01040557]]

 W12: 
 [[ 0.99162886]
 [ 0.99162886]]

 W23: 
 [[ 0.50244196]
 [ 0.50244196]
 [ 0.0006450


 
 rodada 2255 :

 gradW12: 
 [[-0.13126802]
 [-0.13126802]]

 gradW23: 
 [[ 0.03868802]
 [ 0.03868802]
 [ 0.01009499]]

 W12: 
 [[ 0.991882]
 [ 0.991882]]

 W23: 
 [[ 0.50236733]
 [ 0.50236733]
 [ 0.00062561]]

 
 rodada 2256 :

 gradW12: 
 [[-0.1311629]
 [-0.1311629]]

 gradW23: 
 [[ 0.03865638]
 [ 0.03865638]
 [ 0.01008694]]

 W12: 
 [[ 0.99188856]
 [ 0.99188856]]

 W23: 
 [[ 0.5023654 ]
 [ 0.5023654 ]
 [ 0.00062511]]

 
 rodada 2257 :

 gradW12: 
 [[-0.13105787]
 [-0.13105787]]

 gradW23: 
 [[ 0.03862476]
 [ 0.03862476]
 [ 0.0100789 ]]

 W12: 
 [[ 0.99189511]
 [ 0.99189511]]

 W23: 
 [[ 0.50236347]
 [ 0.50236347]
 [ 0.0006246 ]]

 
 rodada 2258 :

 gradW12: 
 [[-0.13095292]
 [-0.13095292]]

 gradW23: 
 [[ 0.03859316]
 [ 0.03859316]
 [ 0.01007086]]

 W12: 
 [[ 0.99190166]
 [ 0.99190166]]

 W23: 
 [[ 0.50236154]
 [ 0.50236154]
 [ 0.0006241 ]]

 
 rodada 2259 :

 gradW12: 
 [[-0.13084805]
 [-0.13084805]]

 gradW23: 
 [[ 0.0385616 ]
 [ 0.0385616 ]
 [ 0.01006283]]

 W12: 
 [[ 0.9919082

 rodada 2308 :

 gradW12: 
 [[-0.12580931]
 [-0.12580931]]

 gradW23: 
 [[ 0.03704612]
 [ 0.03704612]
 [ 0.00967691]]

 W12: 
 [[ 0.99222244]
 [ 0.99222244]]

 W23: 
 [[ 0.50226704]
 [ 0.50226704]
 [ 0.00059943]]

 
 rodada 2309 :

 gradW12: 
 [[-0.12570848]
 [-0.12570848]]

 gradW23: 
 [[ 0.03701583]
 [ 0.03701583]
 [ 0.00966918]]

 W12: 
 [[ 0.99222873]
 [ 0.99222873]]

 W23: 
 [[ 0.50226519]
 [ 0.50226519]
 [ 0.00059894]]

 
 rodada 2310 :

 gradW12: 
 [[-0.12560774]
 [-0.12560774]]

 gradW23: 
 [[ 0.03698555]
 [ 0.03698555]
 [ 0.00966147]]

 W12: 
 [[ 0.99223501]
 [ 0.99223501]]

 W23: 
 [[ 0.50226334]
 [ 0.50226334]
 [ 0.00059846]]

 
 rodada 2311 :

 gradW12: 
 [[-0.12550708]
 [-0.12550708]]

 gradW23: 
 [[ 0.03695531]
 [ 0.03695531]
 [ 0.00965376]]

 W12: 
 [[ 0.99224128]
 [ 0.99224128]]

 W23: 
 [[ 0.50226149]
 [ 0.50226149]
 [ 0.00059798]]

 
 rodada 2312 :

 gradW12: 
 [[-0.1254065]
 [-0.1254065]]

 gradW23: 
 [[ 0.03692508]
 [ 0.03692508]
 [ 0.00964605]]

 W12: 
 [[ 0.992247

 rodada 2369 :

 gradW12: 
 [[-0.11980242]
 [-0.11980242]]

 gradW23: 
 [[ 0.03524273]
 [ 0.03524273]
 [ 0.00921666]]

 W12: 
 [[ 0.99259677]
 [ 0.99259677]]

 W23: 
 [[ 0.50215687]
 [ 0.50215687]
 [ 0.00057063]]

 
 rodada 2370 :

 gradW12: 
 [[-0.11970633]
 [-0.11970633]]

 gradW23: 
 [[ 0.03521391]
 [ 0.03521391]
 [ 0.0092093 ]]

 W12: 
 [[ 0.99260276]
 [ 0.99260276]]

 W23: 
 [[ 0.50215511]
 [ 0.50215511]
 [ 0.00057017]]

 
 rodada 2371 :

 gradW12: 
 [[-0.11961032]
 [-0.11961032]]

 gradW23: 
 [[ 0.03518512]
 [ 0.03518512]
 [ 0.00920194]]

 W12: 
 [[ 0.99260874]
 [ 0.99260874]]

 W23: 
 [[ 0.50215335]
 [ 0.50215335]
 [ 0.00056971]]

 
 rodada 2372 :

 gradW12: 
 [[-0.11951439]
 [-0.11951439]]

 gradW23: 
 [[ 0.03515635]
 [ 0.03515635]
 [ 0.00919459]]

 W12: 
 [[ 0.99261472]
 [ 0.99261472]]

 W23: 
 [[ 0.50215159]
 [ 0.50215159]
 [ 0.00056925]]

 
 rodada 2373 :

 gradW12: 
 [[-0.11941853]
 [-0.11941853]]

 gradW23: 
 [[ 0.0351276 ]
 [ 0.0351276 ]
 [ 0.00918724]]

 W12: 
 [[ 0.9926


 
 rodada 2420 :

 gradW12: 
 [[-0.11499752]
 [-0.11499752]]

 gradW23: 
 [[ 0.03380274]
 [ 0.03380274]
 [ 0.00884838]]

 W12: 
 [[ 0.99289598]
 [ 0.99289598]]

 W23: 
 [[ 0.50206888]
 [ 0.50206888]
 [ 0.00054761]]

 
 rodada 2421 :

 gradW12: 
 [[-0.11490522]
 [-0.11490522]]

 gradW23: 
 [[ 0.0337751 ]
 [ 0.0337751 ]
 [ 0.00884131]]

 W12: 
 [[ 0.99290173]
 [ 0.99290173]]

 W23: 
 [[ 0.50206719]
 [ 0.50206719]
 [ 0.00054717]]

 
 rodada 2422 :

 gradW12: 
 [[-0.11481301]
 [-0.11481301]]

 gradW23: 
 [[ 0.03374749]
 [ 0.03374749]
 [ 0.00883424]]

 W12: 
 [[ 0.99290747]
 [ 0.99290747]]

 W23: 
 [[ 0.50206551]
 [ 0.50206551]
 [ 0.00054673]]

 
 rodada 2423 :

 gradW12: 
 [[-0.11472086]
 [-0.11472086]]

 gradW23: 
 [[ 0.0337199 ]
 [ 0.0337199 ]
 [ 0.00882717]]

 W12: 
 [[ 0.9929132]
 [ 0.9929132]]

 W23: 
 [[ 0.50206382]
 [ 0.50206382]
 [ 0.00054629]]

 
 rodada 2424 :

 gradW12: 
 [[-0.11462879]
 [-0.11462879]]

 gradW23: 
 [[ 0.03369233]
 [ 0.03369233]
 [ 0.00882012]]

 W12: 
 [[ 0.992

 rodada 2477 :

 gradW12: 
 [[-0.10985161]
 [-0.10985161]]

 gradW23: 
 [[ 0.03226306]
 [ 0.03226306]
 [ 0.00845384]]

 W12: 
 [[ 0.99321621]
 [ 0.99321621]]

 W23: 
 [[ 0.50197479]
 [ 0.50197479]
 [ 0.00052297]]

 
 rodada 2478 :

 gradW12: 
 [[-0.10976339]
 [-0.10976339]]

 gradW23: 
 [[ 0.03223668]
 [ 0.03223668]
 [ 0.00844707]]

 W12: 
 [[ 0.9932217]
 [ 0.9932217]]

 W23: 
 [[ 0.50197318]
 [ 0.50197318]
 [ 0.00052255]]

 
 rodada 2479 :

 gradW12: 
 [[-0.10967523]
 [-0.10967523]]

 gradW23: 
 [[ 0.03221033]
 [ 0.03221033]
 [ 0.00844031]]

 W12: 
 [[ 0.99322718]
 [ 0.99322718]]

 W23: 
 [[ 0.50197157]
 [ 0.50197157]
 [ 0.00052213]]

 
 rodada 2480 :

 gradW12: 
 [[-0.10958715]
 [-0.10958715]]

 gradW23: 
 [[ 0.032184  ]
 [ 0.032184  ]
 [ 0.00843356]]

 W12: 
 [[ 0.99323266]
 [ 0.99323266]]

 W23: 
 [[ 0.50196996]
 [ 0.50196996]
 [ 0.0005217 ]]

 
 rodada 2481 :

 gradW12: 
 [[-0.10949913]
 [-0.10949913]]

 gradW23: 
 [[ 0.03215769]
 [ 0.03215769]
 [ 0.00842681]]

 W12: 
 [[ 0.993238

 rodada 2537 :

 gradW12: 
 [[-0.1046799]
 [-0.1046799]]

 gradW23: 
 [[ 0.03071826]
 [ 0.03071826]
 [ 0.00805718]]

 W12: 
 [[ 0.99353782]
 [ 0.99353782]]

 W23: 
 [[  5.01880379e-01]
 [  5.01880379e-01]
 [  4.98217600e-04]]

 
 rodada 2538 :

 gradW12: 
 [[-0.10459577]
 [-0.10459577]]

 gradW23: 
 [[ 0.03069315]
 [ 0.03069315]
 [ 0.00805072]]

 W12: 
 [[ 0.99354305]
 [ 0.99354305]]

 W23: 
 [[  5.01878845e-01]
 [  5.01878845e-01]
 [  4.97815064e-04]]

 
 rodada 2539 :

 gradW12: 
 [[-0.10451171]
 [-0.10451171]]

 gradW23: 
 [[ 0.03066806]
 [ 0.03066806]
 [ 0.00804427]]

 W12: 
 [[ 0.99354827]
 [ 0.99354827]]

 W23: 
 [[  5.01877311e-01]
 [  5.01877311e-01]
 [  4.97412850e-04]]

 
 rodada 2540 :

 gradW12: 
 [[-0.10442771]
 [-0.10442771]]

 gradW23: 
 [[ 0.03064299]
 [ 0.03064299]
 [ 0.00803783]]

 W12: 
 [[ 0.99355349]
 [ 0.99355349]]

 W23: 
 [[  5.01875779e-01]
 [  5.01875779e-01]
 [  4.97010959e-04]]

 
 rodada 2541 :

 gradW12: 
 [[-0.10434378]
 [-0.10434378]]

 gradW23: 
 [[ 0.0

 [[  5.01794876e-01]
 [  5.01794876e-01]
 [  4.75780288e-04]]

 
 rodada 2595 :

 gradW12: 
 [[-0.09990901]
 [-0.09990901]]

 gradW23: 
 [[ 0.02929549]
 [ 0.02929549]
 [ 0.00769114]]

 W12: 
 [[ 0.9938343]
 [ 0.9938343]]

 W23: 
 [[  5.01793411e-01]
 [  5.01793411e-01]
 [  4.75395731e-04]]

 
 rodada 2596 :

 gradW12: 
 [[-0.09982866]
 [-0.09982866]]

 gradW23: 
 [[ 0.02927154]
 [ 0.02927154]
 [ 0.00768498]]

 W12: 
 [[ 0.99383929]
 [ 0.99383929]]

 W23: 
 [[  5.01791948e-01]
 [  5.01791948e-01]
 [  4.75011482e-04]]

 
 rodada 2597 :

 gradW12: 
 [[-0.09974838]
 [-0.09974838]]

 gradW23: 
 [[ 0.02924762]
 [ 0.02924762]
 [ 0.00767881]]

 W12: 
 [[ 0.99384428]
 [ 0.99384428]]

 W23: 
 [[  5.01790485e-01]
 [  5.01790485e-01]
 [  4.74627541e-04]]

 
 rodada 2598 :

 gradW12: 
 [[-0.09966816]
 [-0.09966816]]

 gradW23: 
 [[ 0.02922372]
 [ 0.02922372]
 [ 0.00767266]]

 W12: 
 [[ 0.99384926]
 [ 0.99384926]]

 W23: 
 [[  5.01789024e-01]
 [  5.01789024e-01]
 [  4.74243908e-04]]

 
 rodada 2599 

 [[-0.09658876]
 [-0.09658876]]

 gradW23: 
 [[ 0.02830663]
 [ 0.02830663]
 [ 0.00743633]]

 W12: 
 [[ 0.99404052]
 [ 0.99404052]]

 W23: 
 [[  5.01732960e-01]
 [  5.01732960e-01]
 [  4.59519729e-04]]

 
 rodada 2638 :

 gradW12: 
 [[-0.09651105]
 [-0.09651105]]

 gradW23: 
 [[ 0.02828349]
 [ 0.02828349]
 [ 0.00743037]]

 W12: 
 [[ 0.99404534]
 [ 0.99404534]]

 W23: 
 [[  5.01731546e-01]
 [  5.01731546e-01]
 [  4.59148211e-04]]

 
 rodada 2639 :

 gradW12: 
 [[-0.0964334]
 [-0.0964334]]

 gradW23: 
 [[ 0.02826038]
 [ 0.02826038]
 [ 0.00742441]]

 W12: 
 [[ 0.99405016]
 [ 0.99405016]]

 W23: 
 [[  5.01730133e-01]
 [  5.01730133e-01]
 [  4.58776990e-04]]

 
 rodada 2640 :

 gradW12: 
 [[-0.09635581]
 [-0.09635581]]

 gradW23: 
 [[ 0.02823729]
 [ 0.02823729]
 [ 0.00741845]]

 W12: 
 [[ 0.99405498]
 [ 0.99405498]]

 W23: 
 [[  5.01728721e-01]
 [  5.01728721e-01]
 [  4.58406068e-04]]

 
 rodada 2641 :

 gradW12: 
 [[-0.09627829]
 [-0.09627829]]

 gradW23: 
 [[ 0.02821421]
 [ 0.02821421]
 [ 

 [  4.42734759e-04]]

 
 rodada 2684 :

 gradW12: 
 [[-0.09300226]
 [-0.09300226]]

 gradW23: 
 [[ 0.02723967]
 [ 0.02723967]
 [ 0.00716103]]

 W12: 
 [[ 0.99426317]
 [ 0.99426317]]

 W23: 
 [[  5.01667728e-01]
 [  5.01667728e-01]
 [  4.42376707e-04]]

 
 rodada 2685 :

 gradW12: 
 [[-0.0929274]
 [-0.0929274]]

 gradW23: 
 [[ 0.02721741]
 [ 0.02721741]
 [ 0.00715529]]

 W12: 
 [[ 0.99426782]
 [ 0.99426782]]

 W23: 
 [[  5.01666367e-01]
 [  5.01666367e-01]
 [  4.42018943e-04]]

 
 rodada 2686 :

 gradW12: 
 [[-0.09285259]
 [-0.09285259]]

 gradW23: 
 [[ 0.02719517]
 [ 0.02719517]
 [ 0.00714954]]

 W12: 
 [[ 0.99427246]
 [ 0.99427246]]

 W23: 
 [[  5.01665007e-01]
 [  5.01665007e-01]
 [  4.41661466e-04]]

 
 rodada 2687 :

 gradW12: 
 [[-0.09277785]
 [-0.09277785]]

 gradW23: 
 [[ 0.02717295]
 [ 0.02717295]
 [ 0.0071438 ]]

 W12: 
 [[ 0.9942771]
 [ 0.9942771]]

 W23: 
 [[  5.01663648e-01]
 [  5.01663648e-01]
 [  4.41304275e-04]]

 
 rodada 2688 :

 gradW12: 
 [[-0.09270317]
 [-0.09270317


 gradW12: 
 [[-0.08911549]
 [-0.08911549]]

 gradW23: 
 [[ 0.02608479]
 [ 0.02608479]
 [ 0.00686261]]

 W12: 
 [[ 0.99450434]
 [ 0.99450434]]

 W23: 
 [[  5.01597113e-01]
 [  5.01597113e-01]
 [  4.23805603e-04]]

 
 rodada 2738 :

 gradW12: 
 [[-0.08904372]
 [-0.08904372]]

 gradW23: 
 [[ 0.02606348]
 [ 0.02606348]
 [ 0.0068571 ]]

 W12: 
 [[ 0.9945088]
 [ 0.9945088]]

 W23: 
 [[  5.01595809e-01]
 [  5.01595809e-01]
 [  4.23462748e-04]]

 
 rodada 2739 :

 gradW12: 
 [[-0.08897201]
 [-0.08897201]]

 gradW23: 
 [[ 0.02604218]
 [ 0.02604218]
 [ 0.00685159]]

 W12: 
 [[ 0.99451324]
 [ 0.99451324]]

 W23: 
 [[  5.01594507e-01]
 [  5.01594507e-01]
 [  4.23120169e-04]]

 
 rodada 2740 :

 gradW12: 
 [[-0.08890035]
 [-0.08890035]]

 gradW23: 
 [[ 0.02602091]
 [ 0.02602091]
 [ 0.00684609]]

 W12: 
 [[ 0.99451769]
 [ 0.99451769]]

 W23: 
 [[  5.01593206e-01]
 [  5.01593206e-01]
 [  4.22777864e-04]]

 
 rodada 2741 :

 gradW12: 
 [[-0.08882875]
 [-0.08882875]]

 gradW23: 
 [[ 0.02599965]
 [ 0.0

 rodada 2793 :

 gradW12: 
 [[-0.08518305]
 [-0.08518305]]

 gradW23: 
 [[ 0.02491782]
 [ 0.02491782]
 [ 0.0065606 ]]

 W12: 
 [[ 0.99474822]
 [ 0.99474822]]

 W23: 
 [[  5.01525751e-01]
 [  5.01525751e-01]
 [  4.05023779e-04]]

 
 rodada 2794 :

 gradW12: 
 [[-0.08511441]
 [-0.08511441]]

 gradW23: 
 [[ 0.02489747]
 [ 0.02489747]
 [ 0.00655533]]

 W12: 
 [[ 0.99475248]
 [ 0.99475248]]

 W23: 
 [[  5.01524506e-01]
 [  5.01524506e-01]
 [  4.04696012e-04]]

 
 rodada 2795 :

 gradW12: 
 [[-0.08504582]
 [-0.08504582]]

 gradW23: 
 [[ 0.02487713]
 [ 0.02487713]
 [ 0.00655006]]

 W12: 
 [[ 0.99475673]
 [ 0.99475673]]

 W23: 
 [[  5.01523262e-01]
 [  5.01523262e-01]
 [  4.04368509e-04]]

 
 rodada 2796 :

 gradW12: 
 [[-0.08497729]
 [-0.08497729]]

 gradW23: 
 [[ 0.0248568]
 [ 0.0248568]
 [ 0.0065448]]

 W12: 
 [[ 0.99476098]
 [ 0.99476098]]

 W23: 
 [[  5.01522019e-01]
 [  5.01522019e-01]
 [  4.04041269e-04]]

 
 rodada 2797 :

 gradW12: 
 [[-0.08490882]
 [-0.08490882]]

 gradW23: 
 [[ 0.02

 rodada 2848 :

 gradW12: 
 [[-0.08148793]
 [-0.08148793]]

 gradW23: 
 [[ 0.02382264]
 [ 0.02382264]
 [ 0.00627675]]

 W12: 
 [[ 0.99497727]
 [ 0.99497727]]

 W23: 
 [[  5.01458771e-01]
 [  5.01458771e-01]
 [  3.87382345e-04]]

 
 rodada 2849 :

 gradW12: 
 [[-0.08142224]
 [-0.08142224]]

 gradW23: 
 [[ 0.02380318]
 [ 0.02380318]
 [ 0.00627171]]

 W12: 
 [[ 0.99498134]
 [ 0.99498134]]

 W23: 
 [[  5.01457581e-01]
 [  5.01457581e-01]
 [  3.87068760e-04]]

 
 rodada 2850 :

 gradW12: 
 [[-0.0813566]
 [-0.0813566]]

 gradW23: 
 [[ 0.02378374]
 [ 0.02378374]
 [ 0.00626666]]

 W12: 
 [[ 0.9949854]
 [ 0.9949854]]

 W23: 
 [[  5.01456392e-01]
 [  5.01456392e-01]
 [  3.86755427e-04]]

 
 rodada 2851 :

 gradW12: 
 [[-0.08129101]
 [-0.08129101]]

 gradW23: 
 [[ 0.02376431]
 [ 0.02376431]
 [ 0.00626162]]

 W12: 
 [[ 0.99498947]
 [ 0.99498947]]

 W23: 
 [[  5.01455204e-01]
 [  5.01455204e-01]
 [  3.86442345e-04]]

 
 rodada 2852 :

 gradW12: 
 [[-0.08122547]
 [-0.08122547]]

 gradW23: 
 [[ 0.023

 [  3.69006776e-04]]

 
 rodada 2909 :

 gradW12: 
 [[-0.07757494]
 [-0.07757494]]

 gradW23: 
 [[ 0.02266431]
 [ 0.02266431]
 [ 0.00597609]]

 W12: 
 [[ 0.99521969]
 [ 0.99521969]]

 W23: 
 [[  5.01387922e-01]
 [  5.01387922e-01]
 [  3.68707971e-04]]

 
 rodada 2910 :

 gradW12: 
 [[-0.07751237]
 [-0.07751237]]

 gradW23: 
 [[ 0.0226458 ]
 [ 0.0226458 ]
 [ 0.00597128]]

 W12: 
 [[ 0.99522357]
 [ 0.99522357]]

 W23: 
 [[  5.01386790e-01]
 [  5.01386790e-01]
 [  3.68409407e-04]]

 
 rodada 2911 :

 gradW12: 
 [[-0.07744985]
 [-0.07744985]]

 gradW23: 
 [[ 0.02262731]
 [ 0.02262731]
 [ 0.00596648]]

 W12: 
 [[ 0.99522744]
 [ 0.99522744]]

 W23: 
 [[  5.01385659e-01]
 [  5.01385659e-01]
 [  3.68111083e-04]]

 
 rodada 2912 :

 gradW12: 
 [[-0.07738737]
 [-0.07738737]]

 gradW23: 
 [[ 0.02260882]
 [ 0.02260882]
 [ 0.00596168]]

 W12: 
 [[ 0.99523131]
 [ 0.99523131]]

 W23: 
 [[  5.01384528e-01]
 [  5.01384528e-01]
 [  3.67812999e-04]]

 
 rodada 2913 :

 gradW12: 
 [[-0.07732495]
 [-0.0773


 
 rodada 2965 :

 gradW12: 
 [[-0.0741467]
 [-0.0741467]]

 gradW23: 
 [[ 0.02165069]
 [ 0.02165069]
 [ 0.00571262]]

 W12: 
 [[ 0.99543198]
 [ 0.99543198]]

 W23: 
 [[  5.01325917e-01]
 [  5.01325917e-01]
 [  3.52353102e-04]]

 
 rodada 2966 :

 gradW12: 
 [[-0.07408686]
 [-0.07408686]]

 gradW23: 
 [[ 0.021633  ]
 [ 0.021633  ]
 [ 0.00570802]]

 W12: 
 [[ 0.99543568]
 [ 0.99543568]]

 W23: 
 [[  5.01324836e-01]
 [  5.01324836e-01]
 [  3.52067701e-04]]

 
 rodada 2967 :

 gradW12: 
 [[-0.07402707]
 [-0.07402707]]

 gradW23: 
 [[ 0.02161534]
 [ 0.02161534]
 [ 0.00570342]]

 W12: 
 [[ 0.99543938]
 [ 0.99543938]]

 W23: 
 [[  5.01323755e-01]
 [  5.01323755e-01]
 [  3.51782530e-04]]

 
 rodada 2968 :

 gradW12: 
 [[-0.07396734]
 [-0.07396734]]

 gradW23: 
 [[ 0.02159768]
 [ 0.02159768]
 [ 0.00569883]]

 W12: 
 [[ 0.99544308]
 [ 0.99544308]]

 W23: 
 [[  5.01322675e-01]
 [  5.01322675e-01]
 [  3.51497588e-04]]

 
 rodada 2969 :

 gradW12: 
 [[-0.07390764]
 [-0.07390764]]

 gradW23: 
 [[ 

 [ 0.99563842]]

 W23: 
 [[  5.01265652e-01]
 [  5.01265652e-01]
 [  3.36446683e-04]]

 
 rodada 3023 :

 gradW12: 
 [[-0.07075414]
 [-0.07075414]]

 gradW23: 
 [[ 0.02064872]
 [ 0.02064872]
 [ 0.00545182]]

 W12: 
 [[ 0.99564196]
 [ 0.99564196]]

 W23: 
 [[  5.01264620e-01]
 [  5.01264620e-01]
 [  3.36174092e-04]]

 
 rodada 3024 :

 gradW12: 
 [[-0.07069701]
 [-0.07069701]]

 gradW23: 
 [[ 0.02063186]
 [ 0.02063186]
 [ 0.00544743]]

 W12: 
 [[ 0.9956455]
 [ 0.9956455]]

 W23: 
 [[  5.01263588e-01]
 [  5.01263588e-01]
 [  3.35901720e-04]]

 
 rodada 3025 :

 gradW12: 
 [[-0.07063994]
 [-0.07063994]]

 gradW23: 
 [[ 0.02061501]
 [ 0.02061501]
 [ 0.00544304]]

 W12: 
 [[ 0.99564903]
 [ 0.99564903]]

 W23: 
 [[  5.01262557e-01]
 [  5.01262557e-01]
 [  3.35629568e-04]]

 
 rodada 3026 :

 gradW12: 
 [[-0.07058291]
 [-0.07058291]]

 gradW23: 
 [[ 0.02059818]
 [ 0.02059818]
 [ 0.00543866]]

 W12: 
 [[ 0.99565256]
 [ 0.99565256]]

 W23: 
 [[  5.01261528e-01]
 [  5.01261528e-01]
 [  3.3535763

 [[ 0.9958322]
 [ 0.9958322]]

 W23: 
 [[  5.01209115e-01]
 [  5.01209115e-01]
 [  3.21514936e-04]]

 
 rodada 3079 :

 gradW12: 
 [[-0.0676246]
 [-0.0676246]]

 gradW23: 
 [[ 0.01972541]
 [ 0.01972541]
 [ 0.0052112 ]]

 W12: 
 [[ 0.99583558]
 [ 0.99583558]]

 W23: 
 [[  5.01208129e-01]
 [  5.01208129e-01]
 [  3.21254376e-04]]

 
 rodada 3080 :

 gradW12: 
 [[-0.06756998]
 [-0.06756998]]

 gradW23: 
 [[ 0.0197093]
 [ 0.0197093]
 [ 0.005207 ]]

 W12: 
 [[ 0.99583896]
 [ 0.99583896]]

 W23: 
 [[  5.01207144e-01]
 [  5.01207144e-01]
 [  3.20994026e-04]]

 
 rodada 3081 :

 gradW12: 
 [[-0.06751541]
 [-0.06751541]]

 gradW23: 
 [[ 0.01969321]
 [ 0.01969321]
 [ 0.0052028 ]]

 W12: 
 [[ 0.99584234]
 [ 0.99584234]]

 W23: 
 [[  5.01206159e-01]
 [  5.01206159e-01]
 [  3.20733886e-04]]

 
 rodada 3082 :

 gradW12: 
 [[-0.06746088]
 [-0.06746088]]

 gradW23: 
 [[ 0.01967713]
 [ 0.01967713]
 [ 0.00519861]]

 W12: 
 [[ 0.99584571]
 [ 0.99584571]]

 W23: 
 [[  5.01205175e-01]
 [  5.01205175e-01]
 [

 rodada 3135 :

 gradW12: 
 [[-0.0646323]
 [-0.0646323]]

 gradW23: 
 [[ 0.01884346]
 [ 0.01884346]
 [ 0.00498108]]

 W12: 
 [[ 0.99602064]
 [ 0.99602064]]

 W23: 
 [[  5.01154164e-01]
 [  5.01154164e-01]
 [  3.06993326e-04]]

 
 rodada 3136 :

 gradW12: 
 [[-0.06458008]
 [-0.06458008]]

 gradW23: 
 [[ 0.01882808]
 [ 0.01882808]
 [ 0.00497707]]

 W12: 
 [[ 0.99602386]
 [ 0.99602386]]

 W23: 
 [[  5.01153223e-01]
 [  5.01153223e-01]
 [  3.06744473e-04]]

 
 rodada 3137 :

 gradW12: 
 [[-0.0645279]
 [-0.0645279]]

 gradW23: 
 [[ 0.01881271]
 [ 0.01881271]
 [ 0.00497305]]

 W12: 
 [[ 0.99602709]
 [ 0.99602709]]

 W23: 
 [[  5.01152282e-01]
 [  5.01152282e-01]
 [  3.06495820e-04]]

 
 rodada 3138 :

 gradW12: 
 [[-0.06447576]
 [-0.06447576]]

 gradW23: 
 [[ 0.01879735]
 [ 0.01879735]
 [ 0.00496904]]

 W12: 
 [[ 0.99603031]
 [ 0.99603031]]

 W23: 
 [[  5.01151342e-01]
 [  5.01151342e-01]
 [  3.06247368e-04]]

 
 rodada 3139 :

 gradW12: 
 [[-0.06442366]
 [-0.06442366]]

 gradW23: 
 [[ 0.018


 
 rodada 3190 :

 gradW12: 
 [[-0.06182129]
 [-0.06182129]]

 gradW23: 
 [[ 0.01801573]
 [ 0.01801573]
 [ 0.00476487]]

 W12: 
 [[ 0.99619441]
 [ 0.99619441]]

 W23: 
 [[  5.01103512e-01]
 [  5.01103512e-01]
 [  2.93600219e-04]]

 
 rodada 3191 :

 gradW12: 
 [[-0.06177132]
 [-0.06177132]]

 gradW23: 
 [[ 0.01800102]
 [ 0.01800102]
 [ 0.00476103]]

 W12: 
 [[ 0.9961975]
 [ 0.9961975]]

 W23: 
 [[  5.01102612e-01]
 [  5.01102612e-01]
 [  2.93362168e-04]]

 
 rodada 3192 :

 gradW12: 
 [[-0.06172139]
 [-0.06172139]]

 gradW23: 
 [[ 0.01798632]
 [ 0.01798632]
 [ 0.00475718]]

 W12: 
 [[ 0.99620059]
 [ 0.99620059]]

 W23: 
 [[  5.01101712e-01]
 [  5.01101712e-01]
 [  2.93124309e-04]]

 
 rodada 3193 :

 gradW12: 
 [[-0.0616715]
 [-0.0616715]]

 gradW23: 
 [[ 0.01797164]
 [ 0.01797164]
 [ 0.00475335]]

 W12: 
 [[ 0.99620367]
 [ 0.99620367]]

 W23: 
 [[  5.01100814e-01]
 [  5.01100814e-01]
 [  2.92886641e-04]]

 
 rodada 3194 :

 gradW12: 
 [[-0.06162165]
 [-0.06162165]]

 gradW23: 
 [[ 0.

 [[-0.05932322]
 [-0.05932322]]

 gradW23: 
 [[ 0.01728077]
 [ 0.01728077]
 [ 0.00457269]]

 W12: 
 [[ 0.99634879]
 [ 0.99634879]]

 W23: 
 [[  5.01058534e-01]
 [  5.01058534e-01]
 [  2.81701296e-04]]

 
 rodada 3242 :

 gradW12: 
 [[-0.05927525]
 [-0.05927525]]

 gradW23: 
 [[ 0.01726666]
 [ 0.01726666]
 [ 0.004569  ]]

 W12: 
 [[ 0.99635175]
 [ 0.99635175]]

 W23: 
 [[  5.01057670e-01]
 [  5.01057670e-01]
 [  2.81472846e-04]]

 
 rodada 3243 :

 gradW12: 
 [[-0.05922732]
 [-0.05922732]]

 gradW23: 
 [[ 0.01725257]
 [ 0.01725257]
 [ 0.00456531]]

 W12: 
 [[ 0.99635471]
 [ 0.99635471]]

 W23: 
 [[  5.01056808e-01]
 [  5.01056808e-01]
 [  2.81244581e-04]]

 
 rodada 3244 :

 gradW12: 
 [[-0.05917943]
 [-0.05917943]]

 gradW23: 
 [[ 0.01723848]
 [ 0.01723848]
 [ 0.00456163]]

 W12: 
 [[ 0.99635767]
 [ 0.99635767]]

 W23: 
 [[  5.01055946e-01]
 [  5.01055946e-01]
 [  2.81016499e-04]]

 
 rodada 3245 :

 gradW12: 
 [[-0.05913158]
 [-0.05913158]]

 gradW23: 
 [[ 0.01722441]
 [ 0.01722441]
 


 
 rodada 3291 :

 gradW12: 
 [[-0.0569714]
 [-0.0569714]]

 gradW23: 
 [[ 0.01658939]
 [ 0.01658939]
 [ 0.00439174]]

 W12: 
 [[ 0.99649408]
 [ 0.99649408]]

 W23: 
 [[  5.01016219e-01]
 [  5.01016219e-01]
 [  2.70501789e-04]]

 
 rodada 3292 :

 gradW12: 
 [[-0.05692532]
 [-0.05692532]]

 gradW23: 
 [[ 0.01657585]
 [ 0.01657585]
 [ 0.00438819]]

 W12: 
 [[ 0.99649692]
 [ 0.99649692]]

 W23: 
 [[  5.01015390e-01]
 [  5.01015390e-01]
 [  2.70282379e-04]]

 
 rodada 3293 :

 gradW12: 
 [[-0.05687928]
 [-0.05687928]]

 gradW23: 
 [[ 0.01656232]
 [ 0.01656232]
 [ 0.00438465]]

 W12: 
 [[ 0.99649977]
 [ 0.99649977]]

 W23: 
 [[  5.01014562e-01]
 [  5.01014562e-01]
 [  2.70063147e-04]]

 
 rodada 3294 :

 gradW12: 
 [[-0.05683328]
 [-0.05683328]]

 gradW23: 
 [[ 0.0165488 ]
 [ 0.0165488 ]
 [ 0.00438111]]

 W12: 
 [[ 0.99650261]
 [ 0.99650261]]

 W23: 
 [[  5.01013735e-01]
 [  5.01013735e-01]
 [  2.69844091e-04]]

 
 rodada 3295 :

 gradW12: 
 [[-0.05678731]
 [-0.05678731]]

 gradW23: 
 [[ 


 
 rodada 3352 :

 gradW12: 
 [[-0.05422718]
 [-0.05422718]]

 gradW23: 
 [[ 0.01578331]
 [ 0.01578331]
 [ 0.00418056]]

 W12: 
 [[ 0.99666355]
 [ 0.99666355]]

 W23: 
 [[  5.00966881e-01]
 [  5.00966881e-01]
 [  2.57436937e-04]]

 
 rodada 3353 :

 gradW12: 
 [[-0.0541833]
 [-0.0541833]]

 gradW23: 
 [[ 0.01577042]
 [ 0.01577042]
 [ 0.00417718]]

 W12: 
 [[ 0.99666626]
 [ 0.99666626]]

 W23: 
 [[  5.00966093e-01]
 [  5.00966093e-01]
 [  2.57228078e-04]]

 
 rodada 3354 :

 gradW12: 
 [[-0.05413946]
 [-0.05413946]]

 gradW23: 
 [[ 0.01575755]
 [ 0.01575755]
 [ 0.00417381]]

 W12: 
 [[ 0.99666897]
 [ 0.99666897]]

 W23: 
 [[  5.00965305e-01]
 [  5.00965305e-01]
 [  2.57019388e-04]]

 
 rodada 3355 :

 gradW12: 
 [[-0.05409566]
 [-0.05409566]]

 gradW23: 
 [[ 0.01574469]
 [ 0.01574469]
 [ 0.00417044]]

 W12: 
 [[ 0.99667167]
 [ 0.99667167]]

 W23: 
 [[  5.00964518e-01]
 [  5.00964518e-01]
 [  2.56810866e-04]]

 
 rodada 3356 :

 gradW12: 
 [[-0.05405189]
 [-0.05405189]]

 gradW23: 
 [[ 

 [-0.05224493]]

 gradW23: 
 [[ 0.01520149]
 [ 0.01520149]
 [ 0.00402799]]

 W12: 
 [[ 0.99678593]
 [ 0.99678593]]

 W23: 
 [[  5.00931267e-01]
 [  5.00931267e-01]
 [  2.48001997e-04]]

 
 rodada 3399 :

 gradW12: 
 [[-0.05220265]
 [-0.05220265]]

 gradW23: 
 [[ 0.01518908]
 [ 0.01518908]
 [ 0.00402474]]

 W12: 
 [[ 0.99678854]
 [ 0.99678854]]

 W23: 
 [[  5.00930508e-01]
 [  5.00930508e-01]
 [  2.47800760e-04]]

 
 rodada 3400 :

 gradW12: 
 [[-0.0521604]
 [-0.0521604]]

 gradW23: 
 [[ 0.01517669]
 [ 0.01517669]
 [ 0.00402148]]

 W12: 
 [[ 0.99679115]
 [ 0.99679115]]

 W23: 
 [[  5.00929749e-01]
 [  5.00929749e-01]
 [  2.47599686e-04]]

 
 rodada 3401 :

 gradW12: 
 [[-0.05211819]
 [-0.05211819]]

 gradW23: 
 [[ 0.0151643 ]
 [ 0.0151643 ]
 [ 0.00401824]]

 W12: 
 [[ 0.99679375]
 [ 0.99679375]]

 W23: 
 [[  5.00928991e-01]
 [  5.00928991e-01]
 [  2.47398774e-04]]

 
 rodada 3402 :

 gradW12: 
 [[-0.05207601]
 [-0.05207601]]

 gradW23: 
 [[ 0.01515193]
 [ 0.01515193]
 [ 0.00401499]]

 W

 rodada 3443 :

 gradW12: 
 [[-0.05037545]
 [-0.05037545]]

 gradW23: 
 [[ 0.01465311]
 [ 0.01465311]
 [ 0.00388409]]

 W12: 
 [[ 0.99690132]
 [ 0.99690132]]

 W23: 
 [[  5.00897698e-01]
 [  5.00897698e-01]
 [  2.39105481e-04]]

 
 rodada 3444 :

 gradW12: 
 [[-0.05033467]
 [-0.05033467]]

 gradW23: 
 [[ 0.01464116]
 [ 0.01464116]
 [ 0.00388095]]

 W12: 
 [[ 0.99690383]
 [ 0.99690383]]

 W23: 
 [[  5.00896966e-01]
 [  5.00896966e-01]
 [  2.38911433e-04]]

 
 rodada 3445 :

 gradW12: 
 [[-0.05029392]
 [-0.05029392]]

 gradW23: 
 [[ 0.01462921]
 [ 0.01462921]
 [ 0.00387781]]

 W12: 
 [[ 0.99690635]
 [ 0.99690635]]

 W23: 
 [[  5.00896235e-01]
 [  5.00896235e-01]
 [  2.38717543e-04]]

 
 rodada 3446 :

 gradW12: 
 [[-0.05025321]
 [-0.05025321]]

 gradW23: 
 [[ 0.01461727]
 [ 0.01461727]
 [ 0.00387468]]

 W12: 
 [[ 0.99690886]
 [ 0.99690886]]

 W23: 
 [[  5.00895504e-01]
 [  5.00895504e-01]
 [  2.38523809e-04]]

 
 rodada 3447 :

 gradW12: 
 [[-0.05021252]
 [-0.05021252]]

 gradW23: 
 [[ 0


 
 rodada 3495 :

 gradW12: 
 [[-0.04829778]
 [-0.04829778]]

 gradW23: 
 [[ 0.01404406]
 [ 0.01404406]
 [ 0.00372414]]

 W12: 
 [[ 0.99702952]
 [ 0.99702952]]

 W23: 
 [[  5.00860413e-01]
 [  5.00860413e-01]
 [  2.29220235e-04]]

 
 rodada 3496 :

 gradW12: 
 [[-0.04825867]
 [-0.04825867]]

 gradW23: 
 [[ 0.0140326 ]
 [ 0.0140326 ]
 [ 0.00372113]]

 W12: 
 [[ 0.99703194]
 [ 0.99703194]]

 W23: 
 [[  5.00859711e-01]
 [  5.00859711e-01]
 [  2.29034179e-04]]

 
 rodada 3497 :

 gradW12: 
 [[-0.0482196]
 [-0.0482196]]

 gradW23: 
 [[ 0.01402115]
 [ 0.01402115]
 [ 0.00371812]]

 W12: 
 [[ 0.99703435]
 [ 0.99703435]]

 W23: 
 [[  5.00859010e-01]
 [  5.00859010e-01]
 [  2.28848273e-04]]

 
 rodada 3498 :

 gradW12: 
 [[-0.04818055]
 [-0.04818055]]

 gradW23: 
 [[ 0.01400971]
 [ 0.01400971]
 [ 0.00371511]]

 W12: 
 [[ 0.99703676]
 [ 0.99703676]]

 W23: 
 [[  5.00858310e-01]
 [  5.00858310e-01]
 [  2.28662518e-04]]

 
 rodada 3499 :

 gradW12: 
 [[-0.04814153]
 [-0.04814153]]

 gradW23: 
 [[ 


 
 rodada 3537 :

 gradW12: 
 [[-0.04668201]
 [-0.04668201]]

 gradW23: 
 [[ 0.01357069]
 [ 0.01357069]
 [ 0.00359973]]

 W12: 
 [[ 0.9971292]
 [ 0.9971292]]

 W23: 
 [[  5.00831432e-01]
 [  5.00831432e-01]
 [  2.21534019e-04]]

 
 rodada 3538 :

 gradW12: 
 [[-0.0466442]
 [-0.0466442]]

 gradW23: 
 [[ 0.01355961]
 [ 0.01355961]
 [ 0.00359682]]

 W12: 
 [[ 0.99713153]
 [ 0.99713153]]

 W23: 
 [[  5.00830754e-01]
 [  5.00830754e-01]
 [  2.21354178e-04]]

 
 rodada 3539 :

 gradW12: 
 [[-0.04660642]
 [-0.04660642]]

 gradW23: 
 [[ 0.01354855]
 [ 0.01354855]
 [ 0.00359391]]

 W12: 
 [[ 0.99713386]
 [ 0.99713386]]

 W23: 
 [[  5.00830077e-01]
 [  5.00830077e-01]
 [  2.21174482e-04]]

 
 rodada 3540 :

 gradW12: 
 [[-0.04656867]
 [-0.04656867]]

 gradW23: 
 [[ 0.01353749]
 [ 0.01353749]
 [ 0.003591  ]]

 W12: 
 [[ 0.99713619]
 [ 0.99713619]]

 W23: 
 [[  5.00829400e-01]
 [  5.00829400e-01]
 [  2.20994932e-04]]

 
 rodada 3541 :

 gradW12: 
 [[-0.04653095]
 [-0.04653095]]

 gradW23: 
 [[ 0.


 
 rodada 3584 :

 gradW12: 
 [[-0.0449375]
 [-0.0449375]]

 gradW23: 
 [[ 0.01305988]
 [ 0.01305988]
 [ 0.0034654 ]]

 W12: 
 [[ 0.9972368]
 [ 0.9972368]]

 W23: 
 [[  5.00800158e-01]
 [  5.00800158e-01]
 [  2.13236843e-04]]

 
 rodada 3585 :

 gradW12: 
 [[-0.0449011]
 [-0.0449011]]

 gradW23: 
 [[ 0.01304922]
 [ 0.01304922]
 [ 0.0034626 ]]

 W12: 
 [[ 0.99723904]
 [ 0.99723904]]

 W23: 
 [[  5.00799505e-01]
 [  5.00799505e-01]
 [  2.13063713e-04]]

 
 rodada 3586 :

 gradW12: 
 [[-0.04486472]
 [-0.04486472]]

 gradW23: 
 [[ 0.01303857]
 [ 0.01303857]
 [ 0.00345979]]

 W12: 
 [[ 0.99724129]
 [ 0.99724129]]

 W23: 
 [[  5.00798854e-01]
 [  5.00798854e-01]
 [  2.12890723e-04]]

 
 rodada 3587 :

 gradW12: 
 [[-0.04482838]
 [-0.04482838]]

 gradW23: 
 [[ 0.01302793]
 [ 0.01302793]
 [ 0.003457  ]]

 W12: 
 [[ 0.99724353]
 [ 0.99724353]]

 W23: 
 [[  5.00798202e-01]
 [  5.00798202e-01]
 [  2.12717873e-04]]

 
 rodada 3588 :

 gradW12: 
 [[-0.04479206]
 [-0.04479206]]

 gradW23: 
 [[ 0.01

 rodada 3623 :

 gradW12: 
 [[-0.04353925]
 [-0.04353925]]

 gradW23: 
 [[ 0.01265066]
 [ 0.01265066]
 [ 0.00335772]]

 W12: 
 [[ 0.99732302]
 [ 0.99732302]]

 W23: 
 [[  5.00775102e-01]
 [  5.00775102e-01]
 [  2.06587543e-04]]

 
 rodada 3624 :

 gradW12: 
 [[-0.04350397]
 [-0.04350397]]

 gradW23: 
 [[ 0.01264034]
 [ 0.01264034]
 [ 0.003355  ]]

 W12: 
 [[ 0.9973252]
 [ 0.9973252]]

 W23: 
 [[  5.00774470e-01]
 [  5.00774470e-01]
 [  2.06419793e-04]]

 
 rodada 3625 :

 gradW12: 
 [[-0.04346872]
 [-0.04346872]]

 gradW23: 
 [[ 0.01263003]
 [ 0.01263003]
 [ 0.00335229]]

 W12: 
 [[ 0.99732737]
 [ 0.99732737]]

 W23: 
 [[  5.00773839e-01]
 [  5.00773839e-01]
 [  2.06252178e-04]]

 
 rodada 3626 :

 gradW12: 
 [[-0.0434335]
 [-0.0434335]]

 gradW23: 
 [[ 0.01261972]
 [ 0.01261972]
 [ 0.00334957]]

 W12: 
 [[ 0.99732954]
 [ 0.99732954]]

 W23: 
 [[  5.00773208e-01]
 [  5.00773208e-01]
 [  2.06084699e-04]]

 
 rodada 3627 :

 gradW12: 
 [[-0.04339831]
 [-0.04339831]]

 gradW23: 
 [[ 0.012


 
 rodada 3670 :

 gradW12: 
 [[-0.04191154]
 [-0.04191154]]

 gradW23: 
 [[ 0.01217453]
 [ 0.01217453]
 [ 0.00323236]]

 W12: 
 [[ 0.99742337]
 [ 0.99742337]]

 W23: 
 [[  5.00745948e-01]
 [  5.00745948e-01]
 [  1.98848265e-04]]

 
 rodada 3671 :

 gradW12: 
 [[-0.04187758]
 [-0.04187758]]

 gradW23: 
 [[ 0.01216459]
 [ 0.01216459]
 [ 0.00322974]]

 W12: 
 [[ 0.99742547]
 [ 0.99742547]]

 W23: 
 [[  5.00745340e-01]
 [  5.00745340e-01]
 [  1.98686778e-04]]

 
 rodada 3672 :

 gradW12: 
 [[-0.04184364]
 [-0.04184364]]

 gradW23: 
 [[ 0.01215467]
 [ 0.01215467]
 [ 0.00322713]]

 W12: 
 [[ 0.99742756]
 [ 0.99742756]]

 W23: 
 [[  5.00744732e-01]
 [  5.00744732e-01]
 [  1.98525422e-04]]

 
 rodada 3673 :

 gradW12: 
 [[-0.04180973]
 [-0.04180973]]

 gradW23: 
 [[ 0.01214475]
 [ 0.01214475]
 [ 0.00322451]]

 W12: 
 [[ 0.99742965]
 [ 0.99742965]]

 W23: 
 [[  5.00744125e-01]
 [  5.00744125e-01]
 [  1.98364196e-04]]

 
 rodada 3674 :

 gradW12: 
 [[-0.04177584]
 [-0.04177584]]

 gradW23: 
 [

 rodada 3729 :

 gradW12: 
 [[-0.03995367]
 [-0.03995367]]

 gradW23: 
 [[ 0.01160214]
 [ 0.01160214]
 [ 0.00308155]]

 W12: 
 [[ 0.99754405]
 [ 0.99754405]]

 W23: 
 [[  5.00710899e-01]
 [  5.00710899e-01]
 [  1.89540784e-04]]

 
 rodada 3730 :

 gradW12: 
 [[-0.03992128]
 [-0.03992128]]

 gradW23: 
 [[ 0.01159267]
 [ 0.01159267]
 [ 0.00307905]]

 W12: 
 [[ 0.99754605]
 [ 0.99754605]]

 W23: 
 [[  5.00710319e-01]
 [  5.00710319e-01]
 [  1.89386831e-04]]

 
 rodada 3731 :

 gradW12: 
 [[-0.03988892]
 [-0.03988892]]

 gradW23: 
 [[ 0.01158322]
 [ 0.01158322]
 [ 0.00307656]]

 W12: 
 [[ 0.99754804]
 [ 0.99754804]]

 W23: 
 [[  5.00709740e-01]
 [  5.00709740e-01]
 [  1.89233003e-04]]

 
 rodada 3732 :

 gradW12: 
 [[-0.03985658]
 [-0.03985658]]

 gradW23: 
 [[ 0.01157377]
 [ 0.01157377]
 [ 0.00307407]]

 W12: 
 [[ 0.99755004]
 [ 0.99755004]]

 W23: 
 [[  5.00709161e-01]
 [  5.00709161e-01]
 [  1.89079300e-04]]

 
 rodada 3733 :

 gradW12: 
 [[-0.03982427]
 [-0.03982427]]

 gradW23: 
 [[ 0

 [[-0.03817959]
 [-0.03817959]]

 gradW23: 
 [[ 0.0110838 ]
 [ 0.0110838 ]
 [ 0.00294488]]

 W12: 
 [[ 0.99765338]
 [ 0.99765338]]

 W23: 
 [[  5.00679157e-01]
 [  5.00679157e-01]
 [  1.81108636e-04]]

 
 rodada 3786 :

 gradW12: 
 [[-0.03814863]
 [-0.03814863]]

 gradW23: 
 [[ 0.01107476]
 [ 0.01107476]
 [ 0.0029425 ]]

 W12: 
 [[ 0.99765528]
 [ 0.99765528]]

 W23: 
 [[  5.00678603e-01]
 [  5.00678603e-01]
 [  1.80961511e-04]]

 
 rodada 3787 :

 gradW12: 
 [[-0.0381177]
 [-0.0381177]]

 gradW23: 
 [[ 0.01106572]
 [ 0.01106572]
 [ 0.00294011]]

 W12: 
 [[ 0.99765719]
 [ 0.99765719]]

 W23: 
 [[  5.00678050e-01]
 [  5.00678050e-01]
 [  1.80814506e-04]]

 
 rodada 3788 :

 gradW12: 
 [[-0.0380868]
 [-0.0380868]]

 gradW23: 
 [[ 0.01105669]
 [ 0.01105669]
 [ 0.00293773]]

 W12: 
 [[ 0.99765909]
 [ 0.99765909]]

 W23: 
 [[  5.00677497e-01]
 [  5.00677497e-01]
 [  1.80667619e-04]]

 
 rodada 3789 :

 gradW12: 
 [[-0.03805591]
 [-0.03805591]]

 gradW23: 
 [[ 0.01104767]
 [ 0.01104767]
 [ 0.

 rodada 3841 :

 gradW12: 
 [[-0.03648391]
 [-0.03648391]]

 gradW23: 
 [[ 0.01058864]
 [ 0.01058864]
 [ 0.00281424]]

 W12: 
 [[ 0.99775784]
 [ 0.99775784]]

 W23: 
 [[  5.00648833e-01]
 [  5.00648833e-01]
 [  1.73050507e-04]]

 
 rodada 3842 :

 gradW12: 
 [[-0.03645433]
 [-0.03645433]]

 gradW23: 
 [[ 0.01058   ]
 [ 0.01058   ]
 [ 0.00281196]]

 W12: 
 [[ 0.99775967]
 [ 0.99775967]]

 W23: 
 [[  5.00648304e-01]
 [  5.00648304e-01]
 [  1.72909909e-04]]

 
 rodada 3843 :

 gradW12: 
 [[-0.03642476]
 [-0.03642476]]

 gradW23: 
 [[ 0.01057137]
 [ 0.01057137]
 [ 0.00280968]]

 W12: 
 [[ 0.99776149]
 [ 0.99776149]]

 W23: 
 [[  5.00647776e-01]
 [  5.00647776e-01]
 [  1.72769425e-04]]

 
 rodada 3844 :

 gradW12: 
 [[-0.03639522]
 [-0.03639522]]

 gradW23: 
 [[ 0.01056275]
 [ 0.01056275]
 [ 0.00280741]]

 W12: 
 [[ 0.99776331]
 [ 0.99776331]]

 W23: 
 [[  5.00647248e-01]
 [  5.00647248e-01]
 [  1.72629055e-04]]

 
 rodada 3845 :

 gradW12: 
 [[-0.0363657]
 [-0.0363657]]

 gradW23: 
 [[ 0.0

 rodada 3896 :

 gradW12: 
 [[-0.03489151]
 [-0.03489151]]

 gradW23: 
 [[ 0.01012389]
 [ 0.01012389]
 [ 0.00269154]]

 W12: 
 [[ 0.99785593]
 [ 0.99785593]]

 W23: 
 [[  5.00620370e-01]
 [  5.00620370e-01]
 [  1.65484372e-04]]

 
 rodada 3897 :

 gradW12: 
 [[-0.0348632]
 [-0.0348632]]

 gradW23: 
 [[ 0.01011563]
 [ 0.01011563]
 [ 0.00268936]]

 W12: 
 [[ 0.99785767]
 [ 0.99785767]]

 W23: 
 [[  5.00619864e-01]
 [  5.00619864e-01]
 [  1.65349904e-04]]

 
 rodada 3898 :

 gradW12: 
 [[-0.03483492]
 [-0.03483492]]

 gradW23: 
 [[ 0.01010738]
 [ 0.01010738]
 [ 0.00268718]]

 W12: 
 [[ 0.99785941]
 [ 0.99785941]]

 W23: 
 [[  5.00619359e-01]
 [  5.00619359e-01]
 [  1.65215545e-04]]

 
 rodada 3899 :

 gradW12: 
 [[-0.03480667]
 [-0.03480667]]

 gradW23: 
 [[ 0.01009913]
 [ 0.01009913]
 [ 0.002685  ]]

 W12: 
 [[ 0.99786115]
 [ 0.99786115]]

 W23: 
 [[  5.00618854e-01]
 [  5.00618854e-01]
 [  1.65081294e-04]]

 
 rodada 3900 :

 gradW12: 
 [[-0.03477843]
 [-0.03477843]]

 gradW23: 
 [[ 0.0


 
 rodada 3955 :

 gradW12: 
 [[-0.03326014]
 [-0.03326014]]

 gradW23: 
 [[ 0.00964801]
 [ 0.00964801]
 [ 0.00256583]]

 W12: 
 [[ 0.99795639]
 [ 0.99795639]]

 W23: 
 [[  5.00591224e-01]
 [  5.00591224e-01]
 [  1.57734364e-04]]

 
 rodada 3956 :

 gradW12: 
 [[-0.03323315]
 [-0.03323315]]

 gradW23: 
 [[ 0.00964014]
 [ 0.00964014]
 [ 0.00256375]]

 W12: 
 [[ 0.99795805]
 [ 0.99795805]]

 W23: 
 [[  5.00590742e-01]
 [  5.00590742e-01]
 [  1.57606177e-04]]

 
 rodada 3957 :

 gradW12: 
 [[-0.03320619]
 [-0.03320619]]

 gradW23: 
 [[ 0.00963227]
 [ 0.00963227]
 [ 0.00256167]]

 W12: 
 [[ 0.99795971]
 [ 0.99795971]]

 W23: 
 [[  5.00590260e-01]
 [  5.00590260e-01]
 [  1.57478093e-04]]

 
 rodada 3958 :

 gradW12: 
 [[-0.03317925]
 [-0.03317925]]

 gradW23: 
 [[ 0.00962442]
 [ 0.00962442]
 [ 0.00255959]]

 W12: 
 [[ 0.99796137]
 [ 0.99796137]]

 W23: 
 [[  5.00589779e-01]
 [  5.00589779e-01]
 [  1.57350113e-04]]

 
 rodada 3959 :

 gradW12: 
 [[-0.03315233]
 [-0.03315233]]

 gradW23: 
 [

 [[  5.00564828e-01]
 [  5.00564828e-01]
 [  1.50713571e-04]]

 
 rodada 4012 :

 gradW12: 
 [[-0.03175625]
 [-0.03175625]]

 gradW23: 
 [[ 0.00920953]
 [ 0.00920953]
 [ 0.00244993]]

 W12: 
 [[ 0.99804899]
 [ 0.99804899]]

 W23: 
 [[  5.00564368e-01]
 [  5.00564368e-01]
 [  1.50591075e-04]]

 
 rodada 4013 :

 gradW12: 
 [[-0.03173048]
 [-0.03173048]]

 gradW23: 
 [[ 0.00920202]
 [ 0.00920202]
 [ 0.00244794]]

 W12: 
 [[ 0.99805057]
 [ 0.99805057]]

 W23: 
 [[  5.00563908e-01]
 [  5.00563908e-01]
 [  1.50468678e-04]]

 
 rodada 4014 :

 gradW12: 
 [[-0.03170473]
 [-0.03170473]]

 gradW23: 
 [[ 0.00919452]
 [ 0.00919452]
 [ 0.00244596]]

 W12: 
 [[ 0.99805216]
 [ 0.99805216]]

 W23: 
 [[  5.00563448e-01]
 [  5.00563448e-01]
 [  1.50346380e-04]]

 
 rodada 4015 :

 gradW12: 
 [[-0.031679]
 [-0.031679]]

 gradW23: 
 [[ 0.00918702]
 [ 0.00918702]
 [ 0.00244397]]

 W12: 
 [[ 0.99805374]
 [ 0.99805374]]

 W23: 
 [[  5.00562989e-01]
 [  5.00562989e-01]
 [  1.50224181e-04]]

 
 rodada 4016 :


 [[ 0.99811759]
 [ 0.99811759]]

 W23: 
 [[  5.00544474e-01]
 [  5.00544474e-01]
 [  1.45298422e-04]]

 
 rodada 4057 :

 gradW12: 
 [[-0.03061697]
 [-0.03061697]]

 gradW23: 
 [[ 0.00887751]
 [ 0.00887751]
 [ 0.00236212]]

 W12: 
 [[ 0.99811912]
 [ 0.99811912]]

 W23: 
 [[  5.00544030e-01]
 [  5.00544030e-01]
 [  1.45180316e-04]]

 
 rodada 4058 :

 gradW12: 
 [[-0.03059212]
 [-0.03059212]]

 gradW23: 
 [[ 0.00887027]
 [ 0.00887027]
 [ 0.0023602 ]]

 W12: 
 [[ 0.99812065]
 [ 0.99812065]]

 W23: 
 [[  5.00543587e-01]
 [  5.00543587e-01]
 [  1.45062306e-04]]

 
 rodada 4059 :

 gradW12: 
 [[-0.03056729]
 [-0.03056729]]

 gradW23: 
 [[ 0.00886303]
 [ 0.00886303]
 [ 0.00235829]]

 W12: 
 [[ 0.99812218]
 [ 0.99812218]]

 W23: 
 [[  5.00543144e-01]
 [  5.00543144e-01]
 [  1.44944392e-04]]

 
 rodada 4060 :

 gradW12: 
 [[-0.03054248]
 [-0.03054248]]

 gradW23: 
 [[ 0.0088558 ]
 [ 0.0088558 ]
 [ 0.00235638]]

 W12: 
 [[ 0.99812371]
 [ 0.99812371]]

 W23: 
 [[  5.00542701e-01]
 [  5.00542701e


 gradW12: 
 [[-0.02963849]
 [-0.02963849]]

 gradW23: 
 [[ 0.00859244]
 [ 0.00859244]
 [ 0.0022867 ]]

 W12: 
 [[ 0.99817935]
 [ 0.99817935]]

 W23: 
 [[  5.00526569e-01]
 [  5.00526569e-01]
 [  1.40533791e-04]]

 
 rodada 4098 :

 gradW12: 
 [[-0.02961444]
 [-0.02961444]]

 gradW23: 
 [[ 0.00858544]
 [ 0.00858544]
 [ 0.00228484]]

 W12: 
 [[ 0.99818083]
 [ 0.99818083]]

 W23: 
 [[  5.00526140e-01]
 [  5.00526140e-01]
 [  1.40419549e-04]]

 
 rodada 4099 :

 gradW12: 
 [[-0.0295904]
 [-0.0295904]]

 gradW23: 
 [[ 0.00857843]
 [ 0.00857843]
 [ 0.00228299]]

 W12: 
 [[ 0.99818231]
 [ 0.99818231]]

 W23: 
 [[  5.00525711e-01]
 [  5.00525711e-01]
 [  1.40305399e-04]]

 
 rodada 4100 :

 gradW12: 
 [[-0.02956638]
 [-0.02956638]]

 gradW23: 
 [[ 0.00857144]
 [ 0.00857144]
 [ 0.00228114]]

 W12: 
 [[ 0.99818379]
 [ 0.99818379]]

 W23: 
 [[  5.00525282e-01]
 [  5.00525282e-01]
 [  1.40191342e-04]]

 
 rodada 4101 :

 gradW12: 
 [[-0.02954238]
 [-0.02954238]]

 gradW23: 
 [[ 0.00856445]
 [ 0.0


 gradW12: 
 [[-0.02834376]
 [-0.02834376]]

 gradW23: 
 [[ 0.00821538]
 [ 0.00821538]
 [ 0.00218689]]

 W12: 
 [[ 0.99825903]
 [ 0.99825903]]

 W23: 
 [[  5.00503472e-01]
 [  5.00503472e-01]
 [  1.34386111e-04]]

 
 rodada 4153 :

 gradW12: 
 [[-0.02832075]
 [-0.02832075]]

 gradW23: 
 [[ 0.00820868]
 [ 0.00820868]
 [ 0.00218512]]

 W12: 
 [[ 0.99826044]
 [ 0.99826044]]

 W23: 
 [[  5.00503061e-01]
 [  5.00503061e-01]
 [  1.34276855e-04]]

 
 rodada 4154 :

 gradW12: 
 [[-0.02829776]
 [-0.02829776]]

 gradW23: 
 [[ 0.00820199]
 [ 0.00820199]
 [ 0.00218335]]

 W12: 
 [[ 0.99826186]
 [ 0.99826186]]

 W23: 
 [[  5.00502651e-01]
 [  5.00502651e-01]
 [  1.34167687e-04]]

 
 rodada 4155 :

 gradW12: 
 [[-0.02827478]
 [-0.02827478]]

 gradW23: 
 [[ 0.0081953 ]
 [ 0.0081953 ]
 [ 0.00218158]]

 W12: 
 [[ 0.99826327]
 [ 0.99826327]]

 W23: 
 [[  5.00502241e-01]
 [  5.00502241e-01]
 [  1.34058609e-04]]

 
 rodada 4156 :

 gradW12: 
 [[-0.02825183]
 [-0.02825183]]

 gradW23: 
 [[ 0.00818861]
 [ 0

 rodada 4196 :

 gradW12: 
 [[-0.02734867]
 [-0.02734867]]

 gradW23: 
 [[ 0.00792569]
 [ 0.00792569]
 [ 0.00211018]]

 W12: 
 [[ 0.99832026]
 [ 0.99832026]]

 W23: 
 [[  5.00485726e-01]
 [  5.00485726e-01]
 [  1.29661743e-04]]

 
 rodada 4197 :

 gradW12: 
 [[-0.02732647]
 [-0.02732647]]

 gradW23: 
 [[ 0.00791922]
 [ 0.00791922]
 [ 0.00210847]]

 W12: 
 [[ 0.99832162]
 [ 0.99832162]]

 W23: 
 [[  5.00485330e-01]
 [  5.00485330e-01]
 [  1.29556319e-04]]

 
 rodada 4198 :

 gradW12: 
 [[-0.02730428]
 [-0.02730428]]

 gradW23: 
 [[ 0.00791277]
 [ 0.00791277]
 [ 0.00210676]]

 W12: 
 [[ 0.99832299]
 [ 0.99832299]]

 W23: 
 [[  5.00484934e-01]
 [  5.00484934e-01]
 [  1.29450981e-04]]

 
 rodada 4199 :

 gradW12: 
 [[-0.02728211]
 [-0.02728211]]

 gradW23: 
 [[ 0.00790631]
 [ 0.00790631]
 [ 0.00210505]]

 W12: 
 [[ 0.99832435]
 [ 0.99832435]]

 W23: 
 [[  5.00484539e-01]
 [  5.00484539e-01]
 [  1.29345729e-04]]

 
 rodada 4200 :

 gradW12: 
 [[-0.02725995]
 [-0.02725995]]

 gradW23: 
 [[ 0

 [[  5.00467079e-01]
 [  5.00467079e-01]
 [  1.24696704e-04]]

 
 rodada 4245 :

 gradW12: 
 [[-0.02628143]
 [-0.02628143]]

 gradW23: 
 [[ 0.00761509]
 [ 0.00761509]
 [ 0.0020279 ]]

 W12: 
 [[ 0.99838592]
 [ 0.99838592]]

 W23: 
 [[  5.00466699e-01]
 [  5.00466699e-01]
 [  1.24595309e-04]]

 
 rodada 4246 :

 gradW12: 
 [[-0.02626008]
 [-0.02626008]]

 gradW23: 
 [[ 0.00760888]
 [ 0.00760888]
 [ 0.00202626]]

 W12: 
 [[ 0.99838723]
 [ 0.99838723]]

 W23: 
 [[  5.00466318e-01]
 [  5.00466318e-01]
 [  1.24493996e-04]]

 
 rodada 4247 :

 gradW12: 
 [[-0.02623876]
 [-0.02623876]]

 gradW23: 
 [[ 0.00760268]
 [ 0.00760268]
 [ 0.00202461]]

 W12: 
 [[ 0.99838854]
 [ 0.99838854]]

 W23: 
 [[  5.00465938e-01]
 [  5.00465938e-01]
 [  1.24392765e-04]]

 
 rodada 4248 :

 gradW12: 
 [[-0.02621745]
 [-0.02621745]]

 gradW23: 
 [[ 0.00759648]
 [ 0.00759648]
 [ 0.00202297]]

 W12: 
 [[ 0.99838985]
 [ 0.99838985]]

 W23: 
 [[  5.00465558e-01]
 [  5.00465558e-01]
 [  1.24291616e-04]]

 
 rodada 424


 
 rodada 4300 :

 gradW12: 
 [[-0.02513286]
 [-0.02513286]]

 gradW23: 
 [[ 0.00728095]
 [ 0.00728095]
 [ 0.00193935]]

 W12: 
 [[ 0.99845657]
 [ 0.99845657]]

 W23: 
 [[  5.00446228e-01]
 [  5.00446228e-01]
 [  1.19143452e-04]]

 
 rodada 4301 :

 gradW12: 
 [[-0.02511245]
 [-0.02511245]]

 gradW23: 
 [[ 0.00727501]
 [ 0.00727501]
 [ 0.00193777]]

 W12: 
 [[ 0.99845783]
 [ 0.99845783]]

 W23: 
 [[  5.00445865e-01]
 [  5.00445865e-01]
 [  1.19046563e-04]]

 
 rodada 4302 :

 gradW12: 
 [[-0.02509205]
 [-0.02509205]]

 gradW23: 
 [[ 0.00726908]
 [ 0.00726908]
 [ 0.0019362 ]]

 W12: 
 [[ 0.99845908]
 [ 0.99845908]]

 W23: 
 [[  5.00445501e-01]
 [  5.00445501e-01]
 [  1.18949753e-04]]

 
 rodada 4303 :

 gradW12: 
 [[-0.02507167]
 [-0.02507167]]

 gradW23: 
 [[ 0.00726315]
 [ 0.00726315]
 [ 0.00193463]]

 W12: 
 [[ 0.99846034]
 [ 0.99846034]]

 W23: 
 [[  5.00445138e-01]
 [  5.00445138e-01]
 [  1.18853022e-04]]

 
 rodada 4304 :

 gradW12: 
 [[-0.02505131]
 [-0.02505131]]

 gradW23: 
 [

 rodada 4356 :

 gradW12: 
 [[-0.02401482]
 [-0.02401482]]

 gradW23: 
 [[ 0.0069558 ]
 [ 0.0069558 ]
 [ 0.00185314]]

 W12: 
 [[ 0.99852534]
 [ 0.99852534]]

 W23: 
 [[  5.00426308e-01]
 [  5.00426308e-01]
 [  1.13837033e-04]]

 
 rodada 4357 :

 gradW12: 
 [[-0.02399531]
 [-0.02399531]]

 gradW23: 
 [[ 0.00695013]
 [ 0.00695013]
 [ 0.00185164]]

 W12: 
 [[ 0.99852654]
 [ 0.99852654]]

 W23: 
 [[  5.00425961e-01]
 [  5.00425961e-01]
 [  1.13744451e-04]]

 
 rodada 4358 :

 gradW12: 
 [[-0.02397582]
 [-0.02397582]]

 gradW23: 
 [[ 0.00694446]
 [ 0.00694446]
 [ 0.00185013]]

 W12: 
 [[ 0.99852774]
 [ 0.99852774]]

 W23: 
 [[  5.00425614e-01]
 [  5.00425614e-01]
 [  1.13651944e-04]]

 
 rodada 4359 :

 gradW12: 
 [[-0.02395634]
 [-0.02395634]]

 gradW23: 
 [[ 0.0069388 ]
 [ 0.0069388 ]
 [ 0.00184863]]

 W12: 
 [[ 0.99852894]
 [ 0.99852894]]

 W23: 
 [[  5.00425267e-01]
 [  5.00425267e-01]
 [  1.13559513e-04]]

 
 rodada 4360 :

 gradW12: 
 [[-0.02393688]
 [-0.02393688]]

 gradW23: 
 [[ 0

 [  1.08678050e-04]]

 
 rodada 4414 :

 gradW12: 
 [[-0.02290909]
 [-0.02290909]]

 gradW23: 
 [[ 0.00663436]
 [ 0.00663436]
 [ 0.00176788]]

 W12: 
 [[ 0.99859334]
 [ 0.99859334]]

 W23: 
 [[  5.00406614e-01]
 [  5.00406614e-01]
 [  1.08589656e-04]]

 
 rodada 4415 :

 gradW12: 
 [[-0.02289047]
 [-0.02289047]]

 gradW23: 
 [[ 0.00662895]
 [ 0.00662895]
 [ 0.00176644]]

 W12: 
 [[ 0.99859448]
 [ 0.99859448]]

 W23: 
 [[  5.00406283e-01]
 [  5.00406283e-01]
 [  1.08501334e-04]]

 
 rodada 4416 :

 gradW12: 
 [[-0.02287188]
 [-0.02287188]]

 gradW23: 
 [[ 0.00662354]
 [ 0.00662354]
 [ 0.00176501]]

 W12: 
 [[ 0.99859563]
 [ 0.99859563]]

 W23: 
 [[  5.00405952e-01]
 [  5.00405952e-01]
 [  1.08413083e-04]]

 
 rodada 4417 :

 gradW12: 
 [[-0.0228533]
 [-0.0228533]]

 gradW23: 
 [[ 0.00661814]
 [ 0.00661814]
 [ 0.00176357]]

 W12: 
 [[ 0.99859677]
 [ 0.99859677]]

 W23: 
 [[  5.00405621e-01]
 [  5.00405621e-01]
 [  1.08324905e-04]]

 
 rodada 4418 :

 gradW12: 
 [[-0.02283473]
 [-0.022834

 [-0.02181862]]

 gradW23: 
 [[ 0.00631746]
 [ 0.00631746]
 [ 0.00168378]]

 W12: 
 [[ 0.99866039]
 [ 0.99866039]]

 W23: 
 [[  5.00387198e-01]
 [  5.00387198e-01]
 [  1.03415288e-04]]

 
 rodada 4475 :

 gradW12: 
 [[-0.0218009]
 [-0.0218009]]

 gradW23: 
 [[ 0.00631231]
 [ 0.00631231]
 [ 0.00168242]]

 W12: 
 [[ 0.99866148]
 [ 0.99866148]]

 W23: 
 [[  5.00386883e-01]
 [  5.00386883e-01]
 [  1.03331168e-04]]

 
 rodada 4476 :

 gradW12: 
 [[-0.02178318]
 [-0.02178318]]

 gradW23: 
 [[ 0.00630716]
 [ 0.00630716]
 [ 0.00168105]]

 W12: 
 [[ 0.99866257]
 [ 0.99866257]]

 W23: 
 [[  5.00386568e-01]
 [  5.00386568e-01]
 [  1.03247115e-04]]

 
 rodada 4477 :

 gradW12: 
 [[-0.02176548]
 [-0.02176548]]

 gradW23: 
 [[ 0.00630202]
 [ 0.00630202]
 [ 0.00167969]]

 W12: 
 [[ 0.99866366]
 [ 0.99866366]]

 W23: 
 [[  5.00386252e-01]
 [  5.00386252e-01]
 [  1.03163131e-04]]

 
 rodada 4478 :

 gradW12: 
 [[-0.0217478]
 [-0.0217478]]

 gradW23: 
 [[ 0.00629688]
 [ 0.00629688]
 [ 0.00167832]]

 W12


 
 rodada 4523 :

 gradW12: 
 [[-0.02096659]
 [-0.02096659]]

 gradW23: 
 [[ 0.00606993]
 [ 0.00606993]
 [ 0.00161807]]

 W12: 
 [[ 0.99871277]
 [ 0.99871277]]

 W23: 
 [[  5.00372032e-01]
 [  5.00372032e-01]
 [  9.93726878e-05]]

 
 rodada 4524 :

 gradW12: 
 [[-0.02094955]
 [-0.02094955]]

 gradW23: 
 [[ 0.00606498]
 [ 0.00606498]
 [ 0.00161676]]

 W12: 
 [[ 0.99871382]
 [ 0.99871382]]

 W23: 
 [[  5.00371729e-01]
 [  5.00371729e-01]
 [  9.92918498e-05]]

 
 rodada 4525 :

 gradW12: 
 [[-0.02093253]
 [-0.02093253]]

 gradW23: 
 [[ 0.00606003]
 [ 0.00606003]
 [ 0.00161545]]

 W12: 
 [[ 0.99871487]
 [ 0.99871487]]

 W23: 
 [[  5.00371426e-01]
 [  5.00371426e-01]
 [  9.92110775e-05]]

 
 rodada 4526 :

 gradW12: 
 [[-0.02091552]
 [-0.02091552]]

 gradW23: 
 [[ 0.00605509]
 [ 0.00605509]
 [ 0.00161413]]

 W12: 
 [[ 0.99871591]
 [ 0.99871591]]

 W23: 
 [[  5.00371123e-01]
 [  5.00371123e-01]
 [  9.91303708e-05]]

 
 rodada 4527 :

 gradW12: 
 [[-0.02089852]
 [-0.02089852]]

 gradW23: 
 [


 
 rodada 4580 :

 gradW12: 
 [[-0.02001712]
 [-0.02001712]]

 gradW23: 
 [[ 0.00579416]
 [ 0.00579416]
 [ 0.00154484]]

 W12: 
 [[ 0.99877114]
 [ 0.99877114]]

 W23: 
 [[  5.00355136e-01]
 [  5.00355136e-01]
 [  9.48681619e-05]]

 
 rodada 4581 :

 gradW12: 
 [[-0.02000085]
 [-0.02000085]]

 gradW23: 
 [[ 0.00578944]
 [ 0.00578944]
 [ 0.00154359]]

 W12: 
 [[ 0.99877214]
 [ 0.99877214]]

 W23: 
 [[  5.00354846e-01]
 [  5.00354846e-01]
 [  9.47909824e-05]]

 
 rodada 4582 :

 gradW12: 
 [[-0.01998459]
 [-0.01998459]]

 gradW23: 
 [[ 0.00578472]
 [ 0.00578472]
 [ 0.00154234]]

 W12: 
 [[ 0.99877314]
 [ 0.99877314]]

 W23: 
 [[  5.00354557e-01]
 [  5.00354557e-01]
 [  9.47138656e-05]]

 
 rodada 4583 :

 gradW12: 
 [[-0.01996835]
 [-0.01996835]]

 gradW23: 
 [[ 0.00578   ]
 [ 0.00578   ]
 [ 0.00154108]]

 W12: 
 [[ 0.99877414]
 [ 0.99877414]]

 W23: 
 [[  5.00354268e-01]
 [  5.00354268e-01]
 [  9.46368114e-05]]

 
 rodada 4584 :

 gradW12: 
 [[-0.01995212]
 [-0.01995212]]

 gradW23: 
 [

 [[ 0.998824]
 [ 0.998824]]

 W23: 
 [[  5.00339837e-01]
 [  5.00339837e-01]
 [  9.07889294e-05]]

 
 rodada 4635 :

 gradW12: 
 [[-0.01914164]
 [-0.01914164]]

 gradW23: 
 [[ 0.00553997]
 [ 0.00553997]
 [ 0.00147732]]

 W12: 
 [[ 0.99882495]
 [ 0.99882495]]

 W23: 
 [[  5.00339560e-01]
 [  5.00339560e-01]
 [  9.07150635e-05]]

 
 rodada 4636 :

 gradW12: 
 [[-0.01912608]
 [-0.01912608]]

 gradW23: 
 [[ 0.00553545]
 [ 0.00553545]
 [ 0.00147612]]

 W12: 
 [[ 0.99882591]
 [ 0.99882591]]

 W23: 
 [[  5.00339284e-01]
 [  5.00339284e-01]
 [  9.06412575e-05]]

 
 rodada 4637 :

 gradW12: 
 [[-0.01911054]
 [-0.01911054]]

 gradW23: 
 [[ 0.00553094]
 [ 0.00553094]
 [ 0.00147492]]

 W12: 
 [[ 0.99882687]
 [ 0.99882687]]

 W23: 
 [[  5.00339007e-01]
 [  5.00339007e-01]
 [  9.05675115e-05]]

 
 rodada 4638 :

 gradW12: 
 [[-0.019095]
 [-0.019095]]

 gradW23: 
 [[ 0.00552643]
 [ 0.00552643]
 [ 0.00147372]]

 W12: 
 [[ 0.99882782]
 [ 0.99882782]]

 W23: 
 [[  5.00338731e-01]
 [  5.00338731e-01]
 [ 

 [[ 0.00533596]
 [ 0.00533596]
 [ 0.00142311]]

 W12: 
 [[ 0.99886815]
 [ 0.99886815]]

 W23: 
 [[  5.00327060e-01]
 [  5.00327060e-01]
 [  8.73813138e-05]]

 
 rodada 4682 :

 gradW12: 
 [[-0.01842384]
 [-0.01842384]]

 gradW23: 
 [[ 0.00533161]
 [ 0.00533161]
 [ 0.00142195]]

 W12: 
 [[ 0.99886907]
 [ 0.99886907]]

 W23: 
 [[  5.00326793e-01]
 [  5.00326793e-01]
 [  8.73102162e-05]]

 
 rodada 4683 :

 gradW12: 
 [[-0.01840886]
 [-0.01840886]]

 gradW23: 
 [[ 0.00532726]
 [ 0.00532726]
 [ 0.0014208 ]]

 W12: 
 [[ 0.99886999]
 [ 0.99886999]]

 W23: 
 [[  5.00326527e-01]
 [  5.00326527e-01]
 [  8.72391764e-05]]

 
 rodada 4684 :

 gradW12: 
 [[-0.0183939]
 [-0.0183939]]

 gradW23: 
 [[ 0.00532292]
 [ 0.00532292]
 [ 0.00141964]]

 W12: 
 [[ 0.99887091]
 [ 0.99887091]]

 W23: 
 [[  5.00326260e-01]
 [  5.00326260e-01]
 [  8.71681942e-05]]

 
 rodada 4685 :

 gradW12: 
 [[-0.01837894]
 [-0.01837894]]

 gradW23: 
 [[ 0.00531858]
 [ 0.00531858]
 [ 0.00141849]]

 W12: 
 [[ 0.99887183]
 [ 0.99


 
 rodada 4743 :

 gradW12: 
 [[-0.01753212]
 [-0.01753212]]

 gradW23: 
 [[ 0.00507283]
 [ 0.00507283]
 [ 0.00135317]]

 W12: 
 [[ 0.99892387]
 [ 0.99892387]]

 W23: 
 [[  5.00310936e-01]
 [  5.00310936e-01]
 [  8.30807427e-05]]

 
 rodada 4744 :

 gradW12: 
 [[-0.01751787]
 [-0.01751787]]

 gradW23: 
 [[ 0.0050687 ]
 [ 0.0050687 ]
 [ 0.00135207]]

 W12: 
 [[ 0.99892475]
 [ 0.99892475]]

 W23: 
 [[  5.00310682e-01]
 [  5.00310682e-01]
 [  8.30131394e-05]]

 
 rodada 4745 :

 gradW12: 
 [[-0.01750362]
 [-0.01750362]]

 gradW23: 
 [[ 0.00506456]
 [ 0.00506456]
 [ 0.00135097]]

 W12: 
 [[ 0.99892562]
 [ 0.99892562]]

 W23: 
 [[  5.00310429e-01]
 [  5.00310429e-01]
 [  8.29455909e-05]]

 
 rodada 4746 :

 gradW12: 
 [[-0.01748939]
 [-0.01748939]]

 gradW23: 
 [[ 0.00506044]
 [ 0.00506044]
 [ 0.00134987]]

 W12: 
 [[ 0.99892649]
 [ 0.99892649]]

 W23: 
 [[  5.00310176e-01]
 [  5.00310176e-01]
 [  8.28780973e-05]]

 
 rodada 4747 :

 gradW12: 
 [[-0.01747517]
 [-0.01747517]]

 gradW23: 
 [


 
 rodada 4807 :

 gradW12: 
 [[-0.01664281]
 [-0.01664281]]

 gradW23: 
 [[ 0.00481483]
 [ 0.00481483]
 [ 0.00128456]]

 W12: 
 [[ 0.99897851]
 [ 0.99897851]]

 W23: 
 [[  5.00295126e-01]
 [  5.00295126e-01]
 [  7.88630379e-05]]

 
 rodada 4808 :

 gradW12: 
 [[-0.01662927]
 [-0.01662927]]

 gradW23: 
 [[ 0.0048109 ]
 [ 0.0048109 ]
 [ 0.00128352]]

 W12: 
 [[ 0.99897935]
 [ 0.99897935]]

 W23: 
 [[  5.00294885e-01]
 [  5.00294885e-01]
 [  7.87988619e-05]]

 
 rodada 4809 :

 gradW12: 
 [[-0.01661575]
 [-0.01661575]]

 gradW23: 
 [[ 0.00480698]
 [ 0.00480698]
 [ 0.00128248]]

 W12: 
 [[ 0.99898018]
 [ 0.99898018]]

 W23: 
 [[  5.00294645e-01]
 [  5.00294645e-01]
 [  7.87347381e-05]]

 
 rodada 4810 :

 gradW12: 
 [[-0.01660224]
 [-0.01660224]]

 gradW23: 
 [[ 0.00480306]
 [ 0.00480306]
 [ 0.00128143]]

 W12: 
 [[ 0.99898101]
 [ 0.99898101]]

 W23: 
 [[  5.00294405e-01]
 [  5.00294405e-01]
 [  7.86706664e-05]]

 
 rodada 4811 :

 gradW12: 
 [[-0.01658874]
 [-0.01658874]]

 gradW23: 
 [

 [[ 0.00457741]
 [ 0.00457741]
 [ 0.00122141]]

 W12: 
 [[ 0.99902881]
 [ 0.99902881]]

 W23: 
 [[  5.00280577e-01]
 [  5.00280577e-01]
 [  7.49811719e-05]]

 
 rodada 4870 :

 gradW12: 
 [[-0.01581137]
 [-0.01581137]]

 gradW23: 
 [[ 0.00457368]
 [ 0.00457368]
 [ 0.00122042]]

 W12: 
 [[ 0.9990296]
 [ 0.9990296]]

 W23: 
 [[  5.00280348e-01]
 [  5.00280348e-01]
 [  7.49201509e-05]]

 
 rodada 4871 :

 gradW12: 
 [[-0.01579851]
 [-0.01579851]]

 gradW23: 
 [[ 0.00456995]
 [ 0.00456995]
 [ 0.00121943]]

 W12: 
 [[ 0.99903039]
 [ 0.99903039]]

 W23: 
 [[  5.00280120e-01]
 [  5.00280120e-01]
 [  7.48591794e-05]]

 
 rodada 4872 :

 gradW12: 
 [[-0.01578566]
 [-0.01578566]]

 gradW23: 
 [[ 0.00456622]
 [ 0.00456622]
 [ 0.00121844]]

 W12: 
 [[ 0.99903118]
 [ 0.99903118]]

 W23: 
 [[  5.00279891e-01]
 [  5.00279891e-01]
 [  7.47982575e-05]]

 
 rodada 4873 :

 gradW12: 
 [[-0.01577282]
 [-0.01577282]]

 gradW23: 
 [[ 0.0045625 ]
 [ 0.0045625 ]
 [ 0.00121745]]

 W12: 
 [[ 0.99903197]
 [ 0.99


 
 rodada 4933 :

 gradW12: 
 [[-0.01502138]
 [-0.01502138]]

 gradW23: 
 [[ 0.00434461]
 [ 0.00434461]
 [ 0.00115947]]

 W12: 
 [[ 0.99907813]
 [ 0.99907813]]

 W23: 
 [[  5.00266311e-01]
 [  5.00266311e-01]
 [  7.11741579e-05]]

 
 rodada 4934 :

 gradW12: 
 [[-0.01500917]
 [-0.01500917]]

 gradW23: 
 [[ 0.00434107]
 [ 0.00434107]
 [ 0.00115853]]

 W12: 
 [[ 0.99907888]
 [ 0.99907888]]

 W23: 
 [[  5.00266094e-01]
 [  5.00266094e-01]
 [  7.11162313e-05]]

 
 rodada 4935 :

 gradW12: 
 [[-0.01499696]
 [-0.01499696]]

 gradW23: 
 [[ 0.00433753]
 [ 0.00433753]
 [ 0.00115759]]

 W12: 
 [[ 0.99907963]
 [ 0.99907963]]

 W23: 
 [[  5.00265877e-01]
 [  5.00265877e-01]
 [  7.10583519e-05]]

 
 rodada 4936 :

 gradW12: 
 [[-0.01498476]
 [-0.01498476]]

 gradW23: 
 [[ 0.004334  ]
 [ 0.004334  ]
 [ 0.00115665]]

 W12: 
 [[ 0.99908038]
 [ 0.99908038]]

 W23: 
 [[  5.00265660e-01]
 [  5.00265660e-01]
 [  7.10005195e-05]]

 
 rodada 4937 :

 gradW12: 
 [[-0.01497258]
 [-0.01497258]]

 gradW23: 
 [

 rodada 4995 :

 gradW12: 
 [[-0.01428241]
 [-0.01428241]]

 gradW23: 
 [[ 0.00413039]
 [ 0.00413039]
 [ 0.00110246]]

 W12: 
 [[ 0.99912352]
 [ 0.99912352]]

 W23: 
 [[  5.00253182e-01]
 [  5.00253182e-01]
 [  6.76703280e-05]]

 
 rodada 4996 :

 gradW12: 
 [[-0.0142708]
 [-0.0142708]]

 gradW23: 
 [[ 0.00412703]
 [ 0.00412703]
 [ 0.00110156]]

 W12: 
 [[ 0.99912424]
 [ 0.99912424]]

 W23: 
 [[  5.00252976e-01]
 [  5.00252976e-01]
 [  6.76152498e-05]]

 
 rodada 4997 :

 gradW12: 
 [[-0.01425919]
 [-0.01425919]]

 gradW23: 
 [[ 0.00412366]
 [ 0.00412366]
 [ 0.00110067]]

 W12: 
 [[ 0.99912495]
 [ 0.99912495]]

 W23: 
 [[  5.00252770e-01]
 [  5.00252770e-01]
 [  6.75602165e-05]]

 
 rodada 4998 :

 gradW12: 
 [[-0.01424759]
 [-0.01424759]]

 gradW23: 
 [[ 0.0041203 ]
 [ 0.0041203 ]
 [ 0.00109977]]

 W12: 
 [[ 0.99912566]
 [ 0.99912566]]

 W23: 
 [[  5.00252564e-01]
 [  5.00252564e-01]
 [  6.75052278e-05]]

 
 rodada 4999 :

 gradW12: 
 [[-0.014236]
 [-0.014236]]

 gradW23: 
 [[ 0.00411